// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	models "git.dhbw.chd.cx/backend/models"
)

// UpdateUserByIDHandlerFunc turns a function with the right signature into a update user by Id handler
type UpdateUserByIDHandlerFunc func(UpdateUserByIDParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateUserByIDHandlerFunc) Handle(params UpdateUserByIDParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// UpdateUserByIDHandler interface for that can handle valid update user by Id params
type UpdateUserByIDHandler interface {
	Handle(UpdateUserByIDParams, *models.Principal) middleware.Responder
}

// NewUpdateUserByID creates a new http.Handler for the update user by Id operation
func NewUpdateUserByID(ctx *middleware.Context, handler UpdateUserByIDHandler) *UpdateUserByID {
	return &UpdateUserByID{Context: ctx, Handler: handler}
}

/*UpdateUserByID swagger:route PATCH /users/{id} users updateUserById

Update a user

*/
type UpdateUserByID struct {
	Context *middleware.Context
	Handler UpdateUserByIDHandler
}

func (o *UpdateUserByID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewUpdateUserByIDParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
