// Code generated by go-swagger; DO NOT EDIT.

package health

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// HealthcheckGetHandlerFunc turns a function with the right signature into a healthcheck get handler
type HealthcheckGetHandlerFunc func(HealthcheckGetParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn HealthcheckGetHandlerFunc) Handle(params HealthcheckGetParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// HealthcheckGetHandler interface for that can handle valid healthcheck get params
type HealthcheckGetHandler interface {
	Handle(HealthcheckGetParams, interface{}) middleware.Responder
}

// NewHealthcheckGet creates a new http.Handler for the healthcheck get operation
func NewHealthcheckGet(ctx *middleware.Context, handler HealthcheckGetHandler) *HealthcheckGet {
	return &HealthcheckGet{Context: ctx, Handler: handler}
}

/*HealthcheckGet swagger:route GET /healthcheck health healthcheckGet

Check Server status

*/
type HealthcheckGet struct {
	Context *middleware.Context
	Handler HealthcheckGetHandler
}

func (o *HealthcheckGet) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewHealthcheckGetParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
