// Code generated by go-swagger; DO NOT EDIT.

package message

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "git.dhbw.chd.cx/savood/backend/models"
)

// CreateNewMessageOKCode is the HTTP code returned for type CreateNewMessageOK
const CreateNewMessageOKCode int = 200

/*CreateNewMessageOK Object found and returned

swagger:response createNewMessageOK
*/
type CreateNewMessageOK struct {

	/*
	  In: Body
	*/
	Payload *models.Message `json:"body,omitempty"`
}

// NewCreateNewMessageOK creates CreateNewMessageOK with default headers values
func NewCreateNewMessageOK() *CreateNewMessageOK {

	return &CreateNewMessageOK{}
}

// WithPayload adds the payload to the create new message o k response
func (o *CreateNewMessageOK) WithPayload(payload *models.Message) *CreateNewMessageOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create new message o k response
func (o *CreateNewMessageOK) SetPayload(payload *models.Message) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateNewMessageOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateNewMessageNotFoundCode is the HTTP code returned for type CreateNewMessageNotFound
const CreateNewMessageNotFoundCode int = 404

/*CreateNewMessageNotFound Invalid parameter input was passed

swagger:response createNewMessageNotFound
*/
type CreateNewMessageNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.InvalidParameterInput `json:"body,omitempty"`
}

// NewCreateNewMessageNotFound creates CreateNewMessageNotFound with default headers values
func NewCreateNewMessageNotFound() *CreateNewMessageNotFound {

	return &CreateNewMessageNotFound{}
}

// WithPayload adds the payload to the create new message not found response
func (o *CreateNewMessageNotFound) WithPayload(payload *models.InvalidParameterInput) *CreateNewMessageNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create new message not found response
func (o *CreateNewMessageNotFound) SetPayload(payload *models.InvalidParameterInput) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateNewMessageNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
