// Code generated by go-swagger; DO NOT EDIT.

package message

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// MessageIDPutHandlerFunc turns a function with the right signature into a message Id put handler
type MessageIDPutHandlerFunc func(MessageIDPutParams) middleware.Responder

// Handle executing the request and returning a response
func (fn MessageIDPutHandlerFunc) Handle(params MessageIDPutParams) middleware.Responder {
	return fn(params)
}

// MessageIDPutHandler interface for that can handle valid message Id put params
type MessageIDPutHandler interface {
	Handle(MessageIDPutParams) middleware.Responder
}

// NewMessageIDPut creates a new http.Handler for the message Id put operation
func NewMessageIDPut(ctx *middleware.Context, handler MessageIDPutHandler) *MessageIDPut {
	return &MessageIDPut{Context: ctx, Handler: handler}
}

/*MessageIDPut swagger:route PUT /message/{id} message messageIdPut

Update an message

*/
type MessageIDPut struct {
	Context *middleware.Context
	Handler MessageIDPutHandler
}

func (o *MessageIDPut) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewMessageIDPutParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
