// Code generated by go-swagger; DO NOT EDIT.

package message

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// UpdateMessageByIDHandlerFunc turns a function with the right signature into a update message by Id handler
type UpdateMessageByIDHandlerFunc func(UpdateMessageByIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateMessageByIDHandlerFunc) Handle(params UpdateMessageByIDParams) middleware.Responder {
	return fn(params)
}

// UpdateMessageByIDHandler interface for that can handle valid update message by Id params
type UpdateMessageByIDHandler interface {
	Handle(UpdateMessageByIDParams) middleware.Responder
}

// NewUpdateMessageByID creates a new http.Handler for the update message by Id operation
func NewUpdateMessageByID(ctx *middleware.Context, handler UpdateMessageByIDHandler) *UpdateMessageByID {
	return &UpdateMessageByID{Context: ctx, Handler: handler}
}

/*UpdateMessageByID swagger:route PATCH /message/{id} message updateMessageById

Update a message

*/
type UpdateMessageByID struct {
	Context *middleware.Context
	Handler UpdateMessageByIDHandler
}

func (o *UpdateMessageByID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewUpdateMessageByIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
