// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	models "git.dhbw.chd.cx/savood/backend/models"
)

// GetAllChatsForOfferingHandlerFunc turns a function with the right signature into a get all chats for offering handler
type GetAllChatsForOfferingHandlerFunc func(GetAllChatsForOfferingParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAllChatsForOfferingHandlerFunc) Handle(params GetAllChatsForOfferingParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetAllChatsForOfferingHandler interface for that can handle valid get all chats for offering params
type GetAllChatsForOfferingHandler interface {
	Handle(GetAllChatsForOfferingParams, *models.Principal) middleware.Responder
}

// NewGetAllChatsForOffering creates a new http.Handler for the get all chats for offering operation
func NewGetAllChatsForOffering(ctx *middleware.Context, handler GetAllChatsForOfferingHandler) *GetAllChatsForOffering {
	return &GetAllChatsForOffering{Context: ctx, Handler: handler}
}

/*GetAllChatsForOffering swagger:route GET /offerings/{id}/chats offerings messages getAllChatsForOffering

Display a user

*/
type GetAllChatsForOffering struct {
	Context *middleware.Context
	Handler GetAllChatsForOfferingHandler
}

func (o *GetAllChatsForOffering) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetAllChatsForOfferingParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
