// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "git.dhbw.chd.cx/savood/backend/models"
)

// GetUsersIDBackgroundimageJpegOKCode is the HTTP code returned for type GetUsersIDBackgroundimageJpegOK
const GetUsersIDBackgroundimageJpegOKCode int = 200

/*GetUsersIDBackgroundimageJpegOK OK

swagger:response getUsersIdBackgroundimageJpegOK
*/
type GetUsersIDBackgroundimageJpegOK struct {

	/*
	  In: Body
	*/
	Payload models.GetUsersIDBackgroundimageJpegOKBody `json:"body,omitempty"`
}

// NewGetUsersIDBackgroundimageJpegOK creates GetUsersIDBackgroundimageJpegOK with default headers values
func NewGetUsersIDBackgroundimageJpegOK() *GetUsersIDBackgroundimageJpegOK {

	return &GetUsersIDBackgroundimageJpegOK{}
}

// WithPayload adds the payload to the get users Id backgroundimage jpeg o k response
func (o *GetUsersIDBackgroundimageJpegOK) WithPayload(payload models.GetUsersIDBackgroundimageJpegOKBody) *GetUsersIDBackgroundimageJpegOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get users Id backgroundimage jpeg o k response
func (o *GetUsersIDBackgroundimageJpegOK) SetPayload(payload models.GetUsersIDBackgroundimageJpegOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUsersIDBackgroundimageJpegOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetUsersIDBackgroundimageJpegNotFoundCode is the HTTP code returned for type GetUsersIDBackgroundimageJpegNotFound
const GetUsersIDBackgroundimageJpegNotFoundCode int = 404

/*GetUsersIDBackgroundimageJpegNotFound The specified resource was not found

swagger:response getUsersIdBackgroundimageJpegNotFound
*/
type GetUsersIDBackgroundimageJpegNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorModel `json:"body,omitempty"`
}

// NewGetUsersIDBackgroundimageJpegNotFound creates GetUsersIDBackgroundimageJpegNotFound with default headers values
func NewGetUsersIDBackgroundimageJpegNotFound() *GetUsersIDBackgroundimageJpegNotFound {

	return &GetUsersIDBackgroundimageJpegNotFound{}
}

// WithPayload adds the payload to the get users Id backgroundimage jpeg not found response
func (o *GetUsersIDBackgroundimageJpegNotFound) WithPayload(payload *models.ErrorModel) *GetUsersIDBackgroundimageJpegNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get users Id backgroundimage jpeg not found response
func (o *GetUsersIDBackgroundimageJpegNotFound) SetPayload(payload *models.ErrorModel) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUsersIDBackgroundimageJpegNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetUsersIDBackgroundimageJpegInternalServerErrorCode is the HTTP code returned for type GetUsersIDBackgroundimageJpegInternalServerError
const GetUsersIDBackgroundimageJpegInternalServerErrorCode int = 500

/*GetUsersIDBackgroundimageJpegInternalServerError Generic Error

swagger:response getUsersIdBackgroundimageJpegInternalServerError
*/
type GetUsersIDBackgroundimageJpegInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorModel `json:"body,omitempty"`
}

// NewGetUsersIDBackgroundimageJpegInternalServerError creates GetUsersIDBackgroundimageJpegInternalServerError with default headers values
func NewGetUsersIDBackgroundimageJpegInternalServerError() *GetUsersIDBackgroundimageJpegInternalServerError {

	return &GetUsersIDBackgroundimageJpegInternalServerError{}
}

// WithPayload adds the payload to the get users Id backgroundimage jpeg internal server error response
func (o *GetUsersIDBackgroundimageJpegInternalServerError) WithPayload(payload *models.ErrorModel) *GetUsersIDBackgroundimageJpegInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get users Id backgroundimage jpeg internal server error response
func (o *GetUsersIDBackgroundimageJpegInternalServerError) SetPayload(payload *models.ErrorModel) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUsersIDBackgroundimageJpegInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
