// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	models "git.dhbw.chd.cx/savood/backend/models"
)

// GetOfferingsIDImageHandlerFunc turns a function with the right signature into a get offerings ID image handler
type GetOfferingsIDImageHandlerFunc func(GetOfferingsIDImageParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetOfferingsIDImageHandlerFunc) Handle(params GetOfferingsIDImageParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetOfferingsIDImageHandler interface for that can handle valid get offerings ID image params
type GetOfferingsIDImageHandler interface {
	Handle(GetOfferingsIDImageParams, *models.Principal) middleware.Responder
}

// NewGetOfferingsIDImage creates a new http.Handler for the get offerings ID image operation
func NewGetOfferingsIDImage(ctx *middleware.Context, handler GetOfferingsIDImageHandler) *GetOfferingsIDImage {
	return &GetOfferingsIDImage{Context: ctx, Handler: handler}
}

/*GetOfferingsIDImage swagger:route GET /offerings/{id}/image offerings image getOfferingsIdImage

Gets the avatar image.

*/
type GetOfferingsIDImage struct {
	Context *middleware.Context
	Handler GetOfferingsIDImageHandler
}

func (o *GetOfferingsIDImage) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetOfferingsIDImageParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
