// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "git.dhbw.chd.cx/savood/backend/models"
)

// GetOfferingIDImageOKCode is the HTTP code returned for type GetOfferingIDImageOK
const GetOfferingIDImageOKCode int = 200

/*GetOfferingIDImageOK OK

swagger:response getOfferingIdImageOK
*/
type GetOfferingIDImageOK struct {
}

// NewGetOfferingIDImageOK creates GetOfferingIDImageOK with default headers values
func NewGetOfferingIDImageOK() *GetOfferingIDImageOK {

	return &GetOfferingIDImageOK{}
}

// WriteResponse to the client
func (o *GetOfferingIDImageOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// GetOfferingIDImageNotFoundCode is the HTTP code returned for type GetOfferingIDImageNotFound
const GetOfferingIDImageNotFoundCode int = 404

/*GetOfferingIDImageNotFound The specified resource was not found

swagger:response getOfferingIdImageNotFound
*/
type GetOfferingIDImageNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorModel `json:"body,omitempty"`
}

// NewGetOfferingIDImageNotFound creates GetOfferingIDImageNotFound with default headers values
func NewGetOfferingIDImageNotFound() *GetOfferingIDImageNotFound {

	return &GetOfferingIDImageNotFound{}
}

// WithPayload adds the payload to the get offering Id image not found response
func (o *GetOfferingIDImageNotFound) WithPayload(payload *models.ErrorModel) *GetOfferingIDImageNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get offering Id image not found response
func (o *GetOfferingIDImageNotFound) SetPayload(payload *models.ErrorModel) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetOfferingIDImageNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetOfferingIDImageInternalServerErrorCode is the HTTP code returned for type GetOfferingIDImageInternalServerError
const GetOfferingIDImageInternalServerErrorCode int = 500

/*GetOfferingIDImageInternalServerError Generic Error

swagger:response getOfferingIdImageInternalServerError
*/
type GetOfferingIDImageInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorModel `json:"body,omitempty"`
}

// NewGetOfferingIDImageInternalServerError creates GetOfferingIDImageInternalServerError with default headers values
func NewGetOfferingIDImageInternalServerError() *GetOfferingIDImageInternalServerError {

	return &GetOfferingIDImageInternalServerError{}
}

// WithPayload adds the payload to the get offering Id image internal server error response
func (o *GetOfferingIDImageInternalServerError) WithPayload(payload *models.ErrorModel) *GetOfferingIDImageInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get offering Id image internal server error response
func (o *GetOfferingIDImageInternalServerError) SetPayload(payload *models.ErrorModel) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetOfferingIDImageInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
