// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "git.dhbw.chd.cx/savood/backend/models"
)

// PostOfferingIDImageNoContentCode is the HTTP code returned for type PostOfferingIDImageNoContent
const PostOfferingIDImageNoContentCode int = 204

/*PostOfferingIDImageNoContent Accepted; No response.

swagger:response postOfferingIdImageNoContent
*/
type PostOfferingIDImageNoContent struct {
}

// NewPostOfferingIDImageNoContent creates PostOfferingIDImageNoContent with default headers values
func NewPostOfferingIDImageNoContent() *PostOfferingIDImageNoContent {

	return &PostOfferingIDImageNoContent{}
}

// WriteResponse to the client
func (o *PostOfferingIDImageNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// PostOfferingIDImageBadRequestCode is the HTTP code returned for type PostOfferingIDImageBadRequest
const PostOfferingIDImageBadRequestCode int = 400

/*PostOfferingIDImageBadRequest Invalid parameter input was passed

swagger:response postOfferingIdImageBadRequest
*/
type PostOfferingIDImageBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.InvalidParameterInput `json:"body,omitempty"`
}

// NewPostOfferingIDImageBadRequest creates PostOfferingIDImageBadRequest with default headers values
func NewPostOfferingIDImageBadRequest() *PostOfferingIDImageBadRequest {

	return &PostOfferingIDImageBadRequest{}
}

// WithPayload adds the payload to the post offering Id image bad request response
func (o *PostOfferingIDImageBadRequest) WithPayload(payload *models.InvalidParameterInput) *PostOfferingIDImageBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post offering Id image bad request response
func (o *PostOfferingIDImageBadRequest) SetPayload(payload *models.InvalidParameterInput) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostOfferingIDImageBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostOfferingIDImageInternalServerErrorCode is the HTTP code returned for type PostOfferingIDImageInternalServerError
const PostOfferingIDImageInternalServerErrorCode int = 500

/*PostOfferingIDImageInternalServerError Generic Error

swagger:response postOfferingIdImageInternalServerError
*/
type PostOfferingIDImageInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorModel `json:"body,omitempty"`
}

// NewPostOfferingIDImageInternalServerError creates PostOfferingIDImageInternalServerError with default headers values
func NewPostOfferingIDImageInternalServerError() *PostOfferingIDImageInternalServerError {

	return &PostOfferingIDImageInternalServerError{}
}

// WithPayload adds the payload to the post offering Id image internal server error response
func (o *PostOfferingIDImageInternalServerError) WithPayload(payload *models.ErrorModel) *PostOfferingIDImageInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post offering Id image internal server error response
func (o *PostOfferingIDImageInternalServerError) SetPayload(payload *models.ErrorModel) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostOfferingIDImageInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
