// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	models "git.dhbw.chd.cx/savood/backend/models"
)

// PostUsersIDImageHandlerFunc turns a function with the right signature into a post users ID image handler
type PostUsersIDImageHandlerFunc func(PostUsersIDImageParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn PostUsersIDImageHandlerFunc) Handle(params PostUsersIDImageParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// PostUsersIDImageHandler interface for that can handle valid post users ID image params
type PostUsersIDImageHandler interface {
	Handle(PostUsersIDImageParams, *models.Principal) middleware.Responder
}

// NewPostUsersIDImage creates a new http.Handler for the post users ID image operation
func NewPostUsersIDImage(ctx *middleware.Context, handler PostUsersIDImageHandler) *PostUsersIDImage {
	return &PostUsersIDImage{Context: ctx, Handler: handler}
}

/*PostUsersIDImage swagger:route POST /users/{id}/image postUsersIdImage

Uploads avatar image.

*/
type PostUsersIDImage struct {
	Context *middleware.Context
	Handler PostUsersIDImageHandler
}

func (o *PostUsersIDImage) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostUsersIDImageParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
