// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "git.dhbw.chd.cx/savood/backend/models"
)

// PostOfferingsIDImageNoContentCode is the HTTP code returned for type PostOfferingsIDImageNoContent
const PostOfferingsIDImageNoContentCode int = 204

/*PostOfferingsIDImageNoContent Accepted; No response.

swagger:response postOfferingsIdImageNoContent
*/
type PostOfferingsIDImageNoContent struct {
}

// NewPostOfferingsIDImageNoContent creates PostOfferingsIDImageNoContent with default headers values
func NewPostOfferingsIDImageNoContent() *PostOfferingsIDImageNoContent {

	return &PostOfferingsIDImageNoContent{}
}

// WriteResponse to the client
func (o *PostOfferingsIDImageNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// PostOfferingsIDImageBadRequestCode is the HTTP code returned for type PostOfferingsIDImageBadRequest
const PostOfferingsIDImageBadRequestCode int = 400

/*PostOfferingsIDImageBadRequest Invalid parameter input was passed

swagger:response postOfferingsIdImageBadRequest
*/
type PostOfferingsIDImageBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.InvalidParameterInput `json:"body,omitempty"`
}

// NewPostOfferingsIDImageBadRequest creates PostOfferingsIDImageBadRequest with default headers values
func NewPostOfferingsIDImageBadRequest() *PostOfferingsIDImageBadRequest {

	return &PostOfferingsIDImageBadRequest{}
}

// WithPayload adds the payload to the post offerings Id image bad request response
func (o *PostOfferingsIDImageBadRequest) WithPayload(payload *models.InvalidParameterInput) *PostOfferingsIDImageBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post offerings Id image bad request response
func (o *PostOfferingsIDImageBadRequest) SetPayload(payload *models.InvalidParameterInput) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostOfferingsIDImageBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostOfferingsIDImageForbiddenCode is the HTTP code returned for type PostOfferingsIDImageForbidden
const PostOfferingsIDImageForbiddenCode int = 403

/*PostOfferingsIDImageForbidden Unauthorized

swagger:response postOfferingsIdImageForbidden
*/
type PostOfferingsIDImageForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorModel `json:"body,omitempty"`
}

// NewPostOfferingsIDImageForbidden creates PostOfferingsIDImageForbidden with default headers values
func NewPostOfferingsIDImageForbidden() *PostOfferingsIDImageForbidden {

	return &PostOfferingsIDImageForbidden{}
}

// WithPayload adds the payload to the post offerings Id image forbidden response
func (o *PostOfferingsIDImageForbidden) WithPayload(payload *models.ErrorModel) *PostOfferingsIDImageForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post offerings Id image forbidden response
func (o *PostOfferingsIDImageForbidden) SetPayload(payload *models.ErrorModel) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostOfferingsIDImageForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostOfferingsIDImageInternalServerErrorCode is the HTTP code returned for type PostOfferingsIDImageInternalServerError
const PostOfferingsIDImageInternalServerErrorCode int = 500

/*PostOfferingsIDImageInternalServerError Generic Error

swagger:response postOfferingsIdImageInternalServerError
*/
type PostOfferingsIDImageInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorModel `json:"body,omitempty"`
}

// NewPostOfferingsIDImageInternalServerError creates PostOfferingsIDImageInternalServerError with default headers values
func NewPostOfferingsIDImageInternalServerError() *PostOfferingsIDImageInternalServerError {

	return &PostOfferingsIDImageInternalServerError{}
}

// WithPayload adds the payload to the post offerings Id image internal server error response
func (o *PostOfferingsIDImageInternalServerError) WithPayload(payload *models.ErrorModel) *PostOfferingsIDImageInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post offerings Id image internal server error response
func (o *PostOfferingsIDImageInternalServerError) SetPayload(payload *models.ErrorModel) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostOfferingsIDImageInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
