// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	models "git.dhbw.chd.cx/savood/backend/models"
)

// PostOfferingsIDImageJpegHandlerFunc turns a function with the right signature into a post offerings ID image jpeg handler
type PostOfferingsIDImageJpegHandlerFunc func(PostOfferingsIDImageJpegParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn PostOfferingsIDImageJpegHandlerFunc) Handle(params PostOfferingsIDImageJpegParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// PostOfferingsIDImageJpegHandler interface for that can handle valid post offerings ID image jpeg params
type PostOfferingsIDImageJpegHandler interface {
	Handle(PostOfferingsIDImageJpegParams, *models.Principal) middleware.Responder
}

// NewPostOfferingsIDImageJpeg creates a new http.Handler for the post offerings ID image jpeg operation
func NewPostOfferingsIDImageJpeg(ctx *middleware.Context, handler PostOfferingsIDImageJpegHandler) *PostOfferingsIDImageJpeg {
	return &PostOfferingsIDImageJpeg{Context: ctx, Handler: handler}
}

/*PostOfferingsIDImageJpeg swagger:route POST /offerings/{id}/image.jpeg offerings image postOfferingsIdImageJpeg

Uploads avatar image.

*/
type PostOfferingsIDImageJpeg struct {
	Context *middleware.Context
	Handler PostOfferingsIDImageJpegHandler
}

func (o *PostOfferingsIDImageJpeg) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostOfferingsIDImageJpegParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
