// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	models "git.dhbw.chd.cx/savood/backend/models"
)

// PostUsersIDImageJpegHandlerFunc turns a function with the right signature into a post users ID image jpeg handler
type PostUsersIDImageJpegHandlerFunc func(PostUsersIDImageJpegParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn PostUsersIDImageJpegHandlerFunc) Handle(params PostUsersIDImageJpegParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// PostUsersIDImageJpegHandler interface for that can handle valid post users ID image jpeg params
type PostUsersIDImageJpegHandler interface {
	Handle(PostUsersIDImageJpegParams, *models.Principal) middleware.Responder
}

// NewPostUsersIDImageJpeg creates a new http.Handler for the post users ID image jpeg operation
func NewPostUsersIDImageJpeg(ctx *middleware.Context, handler PostUsersIDImageJpegHandler) *PostUsersIDImageJpeg {
	return &PostUsersIDImageJpeg{Context: ctx, Handler: handler}
}

/*PostUsersIDImageJpeg swagger:route POST /users/{id}/image.jpeg users image postUsersIdImageJpeg

Uploads avatar image.

*/
type PostUsersIDImageJpeg struct {
	Context *middleware.Context
	Handler PostUsersIDImageJpegHandler
}

func (o *PostUsersIDImageJpeg) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostUsersIDImageJpegParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
