// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "git.dhbw.chd.cx/savood/backend/models"
)

// PostUsersIDImageJpegNoContentCode is the HTTP code returned for type PostUsersIDImageJpegNoContent
const PostUsersIDImageJpegNoContentCode int = 204

/*PostUsersIDImageJpegNoContent Accepted; No response.

swagger:response postUsersIdImageJpegNoContent
*/
type PostUsersIDImageJpegNoContent struct {
}

// NewPostUsersIDImageJpegNoContent creates PostUsersIDImageJpegNoContent with default headers values
func NewPostUsersIDImageJpegNoContent() *PostUsersIDImageJpegNoContent {

	return &PostUsersIDImageJpegNoContent{}
}

// WriteResponse to the client
func (o *PostUsersIDImageJpegNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// PostUsersIDImageJpegBadRequestCode is the HTTP code returned for type PostUsersIDImageJpegBadRequest
const PostUsersIDImageJpegBadRequestCode int = 400

/*PostUsersIDImageJpegBadRequest Invalid parameter input was passed

swagger:response postUsersIdImageJpegBadRequest
*/
type PostUsersIDImageJpegBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.InvalidParameterInput `json:"body,omitempty"`
}

// NewPostUsersIDImageJpegBadRequest creates PostUsersIDImageJpegBadRequest with default headers values
func NewPostUsersIDImageJpegBadRequest() *PostUsersIDImageJpegBadRequest {

	return &PostUsersIDImageJpegBadRequest{}
}

// WithPayload adds the payload to the post users Id image jpeg bad request response
func (o *PostUsersIDImageJpegBadRequest) WithPayload(payload *models.InvalidParameterInput) *PostUsersIDImageJpegBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post users Id image jpeg bad request response
func (o *PostUsersIDImageJpegBadRequest) SetPayload(payload *models.InvalidParameterInput) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostUsersIDImageJpegBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostUsersIDImageJpegForbiddenCode is the HTTP code returned for type PostUsersIDImageJpegForbidden
const PostUsersIDImageJpegForbiddenCode int = 403

/*PostUsersIDImageJpegForbidden Unauthorized

swagger:response postUsersIdImageJpegForbidden
*/
type PostUsersIDImageJpegForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorModel `json:"body,omitempty"`
}

// NewPostUsersIDImageJpegForbidden creates PostUsersIDImageJpegForbidden with default headers values
func NewPostUsersIDImageJpegForbidden() *PostUsersIDImageJpegForbidden {

	return &PostUsersIDImageJpegForbidden{}
}

// WithPayload adds the payload to the post users Id image jpeg forbidden response
func (o *PostUsersIDImageJpegForbidden) WithPayload(payload *models.ErrorModel) *PostUsersIDImageJpegForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post users Id image jpeg forbidden response
func (o *PostUsersIDImageJpegForbidden) SetPayload(payload *models.ErrorModel) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostUsersIDImageJpegForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostUsersIDImageJpegInternalServerErrorCode is the HTTP code returned for type PostUsersIDImageJpegInternalServerError
const PostUsersIDImageJpegInternalServerErrorCode int = 500

/*PostUsersIDImageJpegInternalServerError Generic Error

swagger:response postUsersIdImageJpegInternalServerError
*/
type PostUsersIDImageJpegInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorModel `json:"body,omitempty"`
}

// NewPostUsersIDImageJpegInternalServerError creates PostUsersIDImageJpegInternalServerError with default headers values
func NewPostUsersIDImageJpegInternalServerError() *PostUsersIDImageJpegInternalServerError {

	return &PostUsersIDImageJpegInternalServerError{}
}

// WithPayload adds the payload to the post users Id image jpeg internal server error response
func (o *PostUsersIDImageJpegInternalServerError) WithPayload(payload *models.ErrorModel) *PostUsersIDImageJpegInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post users Id image jpeg internal server error response
func (o *PostUsersIDImageJpegInternalServerError) SetPayload(payload *models.ErrorModel) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostUsersIDImageJpegInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
