// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"
	"strings"

	errors "github.com/go-openapi/errors"
	loads "github.com/go-openapi/loads"
	runtime "github.com/go-openapi/runtime"
	middleware "github.com/go-openapi/runtime/middleware"
	security "github.com/go-openapi/runtime/security"
	spec "github.com/go-openapi/spec"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"git.dhbw.chd.cx/savood/backend/restapi/operations/feed"
	"git.dhbw.chd.cx/savood/backend/restapi/operations/health"
	"git.dhbw.chd.cx/savood/backend/restapi/operations/message"
	"git.dhbw.chd.cx/savood/backend/restapi/operations/offering"
	"git.dhbw.chd.cx/savood/backend/restapi/operations/profile"
)

// NewSavoodAPI creates a new Savood instance
func NewSavoodAPI(spec *loads.Document) *SavoodAPI {
	return &SavoodAPI{
		handlers:            make(map[string]map[string]http.Handler),
		formats:             strfmt.Default,
		defaultConsumes:     "application/json",
		defaultProduces:     "application/json",
		customConsumers:     make(map[string]runtime.Consumer),
		customProducers:     make(map[string]runtime.Producer),
		ServerShutdown:      func() {},
		spec:                spec,
		ServeError:          errors.ServeError,
		BasicAuthenticator:  security.BasicAuth,
		APIKeyAuthenticator: security.APIKeyAuth,
		BearerAuthenticator: security.BearerAuth,
		JSONConsumer:        runtime.JSONConsumer(),
		JSONProducer:        runtime.JSONProducer(),
		FeedFeedGetHandler: feed.FeedGetHandlerFunc(func(params feed.FeedGetParams) middleware.Responder {
			return middleware.NotImplemented("operation FeedFeedGet has not yet been implemented")
		}),
		HealthHealthcheckGetHandler: health.HealthcheckGetHandlerFunc(func(params health.HealthcheckGetParams) middleware.Responder {
			return middleware.NotImplemented("operation HealthHealthcheckGet has not yet been implemented")
		}),
		MessageMessageIDDeleteHandler: message.MessageIDDeleteHandlerFunc(func(params message.MessageIDDeleteParams) middleware.Responder {
			return middleware.NotImplemented("operation MessageMessageIDDelete has not yet been implemented")
		}),
		MessageMessageIDGetHandler: message.MessageIDGetHandlerFunc(func(params message.MessageIDGetParams) middleware.Responder {
			return middleware.NotImplemented("operation MessageMessageIDGet has not yet been implemented")
		}),
		MessageMessageIDPutHandler: message.MessageIDPutHandlerFunc(func(params message.MessageIDPutParams) middleware.Responder {
			return middleware.NotImplemented("operation MessageMessageIDPut has not yet been implemented")
		}),
		MessageMessagePostHandler: message.MessagePostHandlerFunc(func(params message.MessagePostParams) middleware.Responder {
			return middleware.NotImplemented("operation MessageMessagePost has not yet been implemented")
		}),
		OfferingOfferingIDDeleteHandler: offering.OfferingIDDeleteHandlerFunc(func(params offering.OfferingIDDeleteParams) middleware.Responder {
			return middleware.NotImplemented("operation OfferingOfferingIDDelete has not yet been implemented")
		}),
		OfferingOfferingIDGetHandler: offering.OfferingIDGetHandlerFunc(func(params offering.OfferingIDGetParams) middleware.Responder {
			return middleware.NotImplemented("operation OfferingOfferingIDGet has not yet been implemented")
		}),
		OfferingOfferingIDPutHandler: offering.OfferingIDPutHandlerFunc(func(params offering.OfferingIDPutParams) middleware.Responder {
			return middleware.NotImplemented("operation OfferingOfferingIDPut has not yet been implemented")
		}),
		OfferingOfferingPostHandler: offering.OfferingPostHandlerFunc(func(params offering.OfferingPostParams) middleware.Responder {
			return middleware.NotImplemented("operation OfferingOfferingPost has not yet been implemented")
		}),
		ProfileProfileIDDeleteHandler: profile.ProfileIDDeleteHandlerFunc(func(params profile.ProfileIDDeleteParams) middleware.Responder {
			return middleware.NotImplemented("operation ProfileProfileIDDelete has not yet been implemented")
		}),
		ProfileProfileIDGetHandler: profile.ProfileIDGetHandlerFunc(func(params profile.ProfileIDGetParams) middleware.Responder {
			return middleware.NotImplemented("operation ProfileProfileIDGet has not yet been implemented")
		}),
		ProfileProfileIDPutHandler: profile.ProfileIDPutHandlerFunc(func(params profile.ProfileIDPutParams) middleware.Responder {
			return middleware.NotImplemented("operation ProfileProfileIDPut has not yet been implemented")
		}),
		ProfileProfilePostHandler: profile.ProfilePostHandlerFunc(func(params profile.ProfilePostParams) middleware.Responder {
			return middleware.NotImplemented("operation ProfileProfilePost has not yet been implemented")
		}),
	}
}

/*SavoodAPI denn nur lebendiges food tut gut */
type SavoodAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	customConsumers map[string]runtime.Consumer
	customProducers map[string]runtime.Producer
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler

	// BasicAuthenticator generates a runtime.Authenticator from the supplied basic auth function.
	// It has a default implemention in the security package, however you can replace it for your particular usage.
	BasicAuthenticator func(security.UserPassAuthentication) runtime.Authenticator
	// APIKeyAuthenticator generates a runtime.Authenticator from the supplied token auth function.
	// It has a default implemention in the security package, however you can replace it for your particular usage.
	APIKeyAuthenticator func(string, string, security.TokenAuthentication) runtime.Authenticator
	// BearerAuthenticator generates a runtime.Authenticator from the supplied bearer token auth function.
	// It has a default implemention in the security package, however you can replace it for your particular usage.
	BearerAuthenticator func(string, security.ScopedTokenAuthentication) runtime.Authenticator

	// JSONConsumer registers a consumer for a "application/json" mime type
	JSONConsumer runtime.Consumer

	// JSONProducer registers a producer for a "application/json" mime type
	JSONProducer runtime.Producer

	// FeedFeedGetHandler sets the operation handler for the feed get operation
	FeedFeedGetHandler feed.FeedGetHandler
	// HealthHealthcheckGetHandler sets the operation handler for the healthcheck get operation
	HealthHealthcheckGetHandler health.HealthcheckGetHandler
	// MessageMessageIDDeleteHandler sets the operation handler for the message Id delete operation
	MessageMessageIDDeleteHandler message.MessageIDDeleteHandler
	// MessageMessageIDGetHandler sets the operation handler for the message Id get operation
	MessageMessageIDGetHandler message.MessageIDGetHandler
	// MessageMessageIDPutHandler sets the operation handler for the message Id put operation
	MessageMessageIDPutHandler message.MessageIDPutHandler
	// MessageMessagePostHandler sets the operation handler for the message post operation
	MessageMessagePostHandler message.MessagePostHandler
	// OfferingOfferingIDDeleteHandler sets the operation handler for the offering Id delete operation
	OfferingOfferingIDDeleteHandler offering.OfferingIDDeleteHandler
	// OfferingOfferingIDGetHandler sets the operation handler for the offering Id get operation
	OfferingOfferingIDGetHandler offering.OfferingIDGetHandler
	// OfferingOfferingIDPutHandler sets the operation handler for the offering Id put operation
	OfferingOfferingIDPutHandler offering.OfferingIDPutHandler
	// OfferingOfferingPostHandler sets the operation handler for the offering post operation
	OfferingOfferingPostHandler offering.OfferingPostHandler
	// ProfileProfileIDDeleteHandler sets the operation handler for the profile Id delete operation
	ProfileProfileIDDeleteHandler profile.ProfileIDDeleteHandler
	// ProfileProfileIDGetHandler sets the operation handler for the profile Id get operation
	ProfileProfileIDGetHandler profile.ProfileIDGetHandler
	// ProfileProfileIDPutHandler sets the operation handler for the profile Id put operation
	ProfileProfileIDPutHandler profile.ProfileIDPutHandler
	// ProfileProfilePostHandler sets the operation handler for the profile post operation
	ProfileProfilePostHandler profile.ProfilePostHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// SetDefaultProduces sets the default produces media type
func (o *SavoodAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *SavoodAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *SavoodAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *SavoodAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *SavoodAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *SavoodAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *SavoodAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the SavoodAPI
func (o *SavoodAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.FeedFeedGetHandler == nil {
		unregistered = append(unregistered, "feed.FeedGetHandler")
	}

	if o.HealthHealthcheckGetHandler == nil {
		unregistered = append(unregistered, "health.HealthcheckGetHandler")
	}

	if o.MessageMessageIDDeleteHandler == nil {
		unregistered = append(unregistered, "message.MessageIDDeleteHandler")
	}

	if o.MessageMessageIDGetHandler == nil {
		unregistered = append(unregistered, "message.MessageIDGetHandler")
	}

	if o.MessageMessageIDPutHandler == nil {
		unregistered = append(unregistered, "message.MessageIDPutHandler")
	}

	if o.MessageMessagePostHandler == nil {
		unregistered = append(unregistered, "message.MessagePostHandler")
	}

	if o.OfferingOfferingIDDeleteHandler == nil {
		unregistered = append(unregistered, "offering.OfferingIDDeleteHandler")
	}

	if o.OfferingOfferingIDGetHandler == nil {
		unregistered = append(unregistered, "offering.OfferingIDGetHandler")
	}

	if o.OfferingOfferingIDPutHandler == nil {
		unregistered = append(unregistered, "offering.OfferingIDPutHandler")
	}

	if o.OfferingOfferingPostHandler == nil {
		unregistered = append(unregistered, "offering.OfferingPostHandler")
	}

	if o.ProfileProfileIDDeleteHandler == nil {
		unregistered = append(unregistered, "profile.ProfileIDDeleteHandler")
	}

	if o.ProfileProfileIDGetHandler == nil {
		unregistered = append(unregistered, "profile.ProfileIDGetHandler")
	}

	if o.ProfileProfileIDPutHandler == nil {
		unregistered = append(unregistered, "profile.ProfileIDPutHandler")
	}

	if o.ProfileProfilePostHandler == nil {
		unregistered = append(unregistered, "profile.ProfilePostHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *SavoodAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *SavoodAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {

	return nil

}

// Authorizer returns the registered authorizer
func (o *SavoodAPI) Authorizer() runtime.Authorizer {

	return nil

}

// ConsumersFor gets the consumers for the specified media types
func (o *SavoodAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {

	result := make(map[string]runtime.Consumer)
	for _, mt := range mediaTypes {
		switch mt {

		case "application/json":
			result["application/json"] = o.JSONConsumer

		}

		if c, ok := o.customConsumers[mt]; ok {
			result[mt] = c
		}
	}
	return result

}

// ProducersFor gets the producers for the specified media types
func (o *SavoodAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {

	result := make(map[string]runtime.Producer)
	for _, mt := range mediaTypes {
		switch mt {

		case "application/json":
			result["application/json"] = o.JSONProducer

		}

		if p, ok := o.customProducers[mt]; ok {
			result[mt] = p
		}
	}
	return result

}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *SavoodAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	if path == "/" {
		path = ""
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the savood API
func (o *SavoodAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *SavoodAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened

	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/feed"] = feed.NewFeedGet(o.context, o.FeedFeedGetHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/healthcheck"] = health.NewHealthcheckGet(o.context, o.HealthHealthcheckGetHandler)

	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/message/{id}"] = message.NewMessageIDDelete(o.context, o.MessageMessageIDDeleteHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/message/{id}"] = message.NewMessageIDGet(o.context, o.MessageMessageIDGetHandler)

	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/message/{id}"] = message.NewMessageIDPut(o.context, o.MessageMessageIDPutHandler)

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/message"] = message.NewMessagePost(o.context, o.MessageMessagePostHandler)

	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/offering/{id}"] = offering.NewOfferingIDDelete(o.context, o.OfferingOfferingIDDeleteHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/offering/{id}"] = offering.NewOfferingIDGet(o.context, o.OfferingOfferingIDGetHandler)

	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/offering/{id}"] = offering.NewOfferingIDPut(o.context, o.OfferingOfferingIDPutHandler)

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/offering"] = offering.NewOfferingPost(o.context, o.OfferingOfferingPostHandler)

	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/profile/{id}"] = profile.NewProfileIDDelete(o.context, o.ProfileProfileIDDeleteHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/profile/{id}"] = profile.NewProfileIDGet(o.context, o.ProfileProfileIDGetHandler)

	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/profile/{id}"] = profile.NewProfileIDPut(o.context, o.ProfileProfileIDPutHandler)

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/profile"] = profile.NewProfilePost(o.context, o.ProfileProfilePostHandler)

}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *SavoodAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middleware as you see fit
func (o *SavoodAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}

// RegisterConsumer allows you to add (or override) a consumer for a media type.
func (o *SavoodAPI) RegisterConsumer(mediaType string, consumer runtime.Consumer) {
	o.customConsumers[mediaType] = consumer
}

// RegisterProducer allows you to add (or override) a producer for a media type.
func (o *SavoodAPI) RegisterProducer(mediaType string, producer runtime.Producer) {
	o.customProducers[mediaType] = producer
}
