// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Savood
denn nur lebendiges food tut gut


    Schemes:
      http
    Host: localhost
    BasePath: /
    Version: 1.0
    License: Apache 2.0 http://www.apache.org/licenses/LICENSE-2.0.html

    Consumes:
    - application/json
    - multipart/form-data

    Produces:
    - application/json
    - image/gif
    - image/jpeg
    - image/png

swagger:meta
*/
package restapi
