// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "https",
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "denn nur lebendiges food tut gut",
    "title": "Savood",
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version": "1.0"
  },
  "host": "virtserver.swaggerhub.com",
  "basePath": "/TimMaa/Savood/1.0",
  "paths": {
    "/chats/": {
      "get": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "messages"
        ],
        "summary": "Get all Chats",
        "operationId": "getAllChats",
        "responses": {
          "200": {
            "description": "Object found and returned",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Chat"
              }
            }
          },
          "400": {
            "$ref": "#/responses/InvalidParameterInput"
          }
        }
      }
    },
    "/chats/{chatID}/messages": {
      "get": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "messages"
        ],
        "summary": "Add a new message",
        "operationId": "getAllMessagesForChat",
        "responses": {
          "200": {
            "description": "Object found and returned",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Message"
              }
            }
          },
          "400": {
            "$ref": "#/responses/InvalidParameterInput"
          }
        }
      },
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "messages"
        ],
        "summary": "Add a new message",
        "operationId": "createNewMessage",
        "parameters": [
          {
            "description": "Message that needs to be added",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Message"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Object found and returned",
            "schema": {
              "$ref": "#/definitions/Message"
            }
          },
          "400": {
            "$ref": "#/responses/InvalidParameterInput"
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "name": "chatID",
          "in": "path",
          "required": true
        }
      ]
    },
    "/chats/{chatID}/messages/{id}": {
      "get": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "messages"
        ],
        "summary": "Display a message",
        "operationId": "getMessageById",
        "responses": {
          "200": {
            "description": "Object found and returned",
            "schema": {
              "$ref": "#/definitions/Message"
            }
          },
          "400": {
            "$ref": "#/responses/InvalidParameterInput"
          }
        }
      },
      "delete": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "messages"
        ],
        "summary": "Delete a message",
        "operationId": "deleteMessageById",
        "responses": {
          "204": {
            "description": "Removed; No response."
          },
          "400": {
            "$ref": "#/responses/InvalidParameterInput"
          }
        }
      },
      "patch": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "messages"
        ],
        "summary": "Update a message",
        "operationId": "updateMessageById",
        "parameters": [
          {
            "description": "New parameters of the message",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Message"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "Accepted; No response."
          },
          "400": {
            "$ref": "#/responses/InvalidParameterInput"
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "name": "chatID",
          "in": "path",
          "required": true
        },
        {
          "type": "string",
          "name": "id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/feed": {
      "get": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "offerings"
        ],
        "summary": "Display a feed of nearby offerings",
        "operationId": "getFeed",
        "parameters": [
          {
            "type": "string",
            "name": "location",
            "in": "query",
            "required": true
          },
          {
            "type": "number",
            "description": "Distance in Meters",
            "name": "distance",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Object found and returned",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Offering"
              }
            }
          },
          "400": {
            "$ref": "#/responses/InvalidParameterInput"
          }
        }
      }
    },
    "/healthcheck": {
      "get": {
        "security": [],
        "produces": [
          "application/json"
        ],
        "tags": [
          "health"
        ],
        "summary": "Check Server status",
        "operationId": "healthcheckGet",
        "responses": {
          "200": {
            "description": "Server is healthy"
          },
          "503": {
            "$ref": "#/responses/Unhealthy"
          }
        }
      }
    },
    "/offerings": {
      "get": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "offerings"
        ],
        "summary": "Display a feed of nearby offerings",
        "operationId": "getOfferings",
        "parameters": [
          {
            "enum": [
              "owned",
              "requested"
            ],
            "type": "string",
            "description": "Filteres offerings by owned or requested",
            "name": "filter",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Object found and returned",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Offering"
              }
            }
          },
          "400": {
            "$ref": "#/responses/InvalidParameterInput"
          }
        }
      },
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "offerings"
        ],
        "summary": "Add a new offering",
        "operationId": "createNewOffering",
        "parameters": [
          {
            "description": "Offering that needs to be added",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Offering"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Object found and returned",
            "schema": {
              "$ref": "#/definitions/Offering"
            }
          },
          "400": {
            "$ref": "#/responses/InvalidParameterInput"
          }
        }
      }
    },
    "/offerings/{id}": {
      "get": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "offerings"
        ],
        "summary": "Display an offering",
        "operationId": "getOfferingById",
        "responses": {
          "200": {
            "description": "Object found and returned",
            "schema": {
              "$ref": "#/definitions/Offering"
            }
          },
          "400": {
            "$ref": "#/responses/InvalidParameterInput"
          }
        }
      },
      "delete": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "offerings"
        ],
        "summary": "Delete an offering",
        "operationId": "deleteOfferingById",
        "responses": {
          "204": {
            "description": "Removed; No response."
          },
          "400": {
            "$ref": "#/responses/InvalidParameterInput"
          }
        }
      },
      "patch": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "offerings"
        ],
        "summary": "Update an offering",
        "operationId": "updateOfferingById",
        "parameters": [
          {
            "description": "New parameters of the offering",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Offering"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "Accepted; No response."
          },
          "400": {
            "$ref": "#/responses/InvalidParameterInput"
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "name": "id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/offerings/{id}/chats": {
      "get": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "offerings",
          "messages"
        ],
        "summary": "Display a user",
        "operationId": "getAllChatsForOffering",
        "responses": {
          "200": {
            "description": "Object found and returned",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Chat"
              }
            }
          },
          "400": {
            "$ref": "#/responses/InvalidParameterInput"
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "name": "id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/users": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "users"
        ],
        "summary": "Add a new user",
        "operationId": "createNewUser",
        "parameters": [
          {
            "description": "User that needs to be added",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/User"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Object found and returned",
            "schema": {
              "$ref": "#/definitions/User"
            }
          },
          "400": {
            "$ref": "#/responses/InvalidParameterInput"
          }
        }
      }
    },
    "/users/{id}": {
      "get": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "users"
        ],
        "summary": "Display a user",
        "operationId": "getUserById",
        "responses": {
          "200": {
            "description": "Object found and returned",
            "schema": {
              "$ref": "#/definitions/User"
            }
          },
          "400": {
            "$ref": "#/responses/InvalidParameterInput"
          }
        }
      },
      "delete": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "users"
        ],
        "summary": "Delete a users",
        "operationId": "deleteUserById",
        "responses": {
          "204": {
            "description": "Removed; No response."
          },
          "400": {
            "$ref": "#/responses/InvalidParameterInput"
          }
        }
      },
      "patch": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "users"
        ],
        "summary": "Update a user",
        "operationId": "updateUserById",
        "parameters": [
          {
            "description": "New parameters of the User",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/User"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "Accepted; No response."
          },
          "400": {
            "$ref": "#/responses/InvalidParameterInput"
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "name": "id",
          "in": "path",
          "required": true
        }
      ]
    }
  },
  "definitions": {
    "Chat": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "offering-id": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "partner": {
          "$ref": "#/definitions/UserShort"
        }
      }
    },
    "ErrorModel": {
      "required": [
        "code",
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int32"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "InvalidParameterInput": {
      "type": "object",
      "required": [
        "attribute",
        "message"
      ],
      "properties": {
        "attribute": {
          "type": "string"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "Message": {
      "type": "object",
      "properties": {
        "content": {
          "type": "string"
        },
        "from": {
          "$ref": "#/definitions/UserShort"
        },
        "time": {
          "type": "string",
          "format": "date-time"
        }
      },
      "xml": {
        "name": "Message"
      }
    },
    "Offering": {
      "type": "object",
      "properties": {
        "avatar-url": {
          "type": "string"
        },
        "best-by-date": {
          "type": "string",
          "format": "date"
        },
        "creator-id": {
          "type": "string"
        },
        "header": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "location": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "requested-by": {
          "type": "integer",
          "format": "int64"
        },
        "time": {
          "type": "string",
          "format": "date-time"
        }
      },
      "xml": {
        "name": "Offering"
      }
    },
    "Principal": {
      "type": "object",
      "properties": {
        "email": {
          "type": "string"
        },
        "userid": {
          "type": "string"
        },
        "username": {
          "type": "string"
        }
      }
    },
    "User": {
      "type": "object",
      "properties": {
        "address": {
          "type": "object",
          "properties": {
            "city": {
              "type": "string"
            },
            "number": {
              "type": "string"
            },
            "street": {
              "type": "string"
            },
            "zip": {
              "type": "integer",
              "format": "int64"
            }
          }
        },
        "avatar-id": {
          "type": "string"
        },
        "background-id": {
          "type": "string"
        },
        "badges": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "description": {
          "type": "string"
        },
        "email": {
          "type": "string",
          "format": "email"
        },
        "firstname": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "lastname": {
          "type": "string"
        },
        "phone": {
          "type": "string",
          "format": "phone"
        }
      },
      "xml": {
        "name": "user"
      },
      "example": {
        "address": {
          "city": "Musterstadt",
          "number": 1337,
          "street": "Musterstraße",
          "zip": 42069
        },
        "avatar-id": "",
        "background-id": "",
        "badges": [
          true,
          false,
          true,
          true,
          true,
          false,
          false,
          true,
          false
        ],
        "description": "I save the wrap and the world",
        "email": "apiteam@swagger.io",
        "firstname": "Marty",
        "id": "5",
        "lastname": "McFlfy",
        "phone": "202-555-0191"
      }
    },
    "UserShort": {
      "type": "object",
      "properties": {
        "avatar-id": {
          "type": "string"
        },
        "firstname": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "lastname": {
          "type": "string"
        }
      },
      "xml": {
        "name": "user"
      },
      "example": {
        "avatar-id": "",
        "firstname": "Marty",
        "id": "5",
        "lastname": "McFlfy"
      }
    }
  },
  "responses": {
    "ErrorResponse": {
      "description": "Generic Error",
      "schema": {
        "$ref": "#/definitions/ErrorModel"
      }
    },
    "InvalidParameterInput": {
      "description": "Invalid parameter input was passed",
      "schema": {
        "$ref": "#/definitions/InvalidParameterInput"
      }
    },
    "NotFound": {
      "description": "The specified resource was not found",
      "schema": {
        "$ref": "#/definitions/ErrorModel"
      }
    },
    "Unauthorized": {
      "description": "Unauthorized",
      "schema": {
        "$ref": "#/definitions/ErrorModel"
      }
    },
    "Unhealthy": {
      "description": "Server is unhealthy",
      "schema": {
        "$ref": "#/definitions/ErrorModel"
      }
    }
  },
  "securityDefinitions": {
    "bearer": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header"
    }
  },
  "security": [
    {
      "bearer": []
    }
  ],
  "tags": [
    {
      "description": "Management of users",
      "name": "users"
    },
    {
      "description": "Management of offered food items",
      "name": "offerings"
    },
    {
      "description": "Operations about users",
      "name": "messages"
    },
    {
      "description": "Operation regarding helath of application",
      "name": "health"
    }
  ]
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "https",
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "denn nur lebendiges food tut gut",
    "title": "Savood",
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version": "1.0"
  },
  "host": "virtserver.swaggerhub.com",
  "basePath": "/TimMaa/Savood/1.0",
  "paths": {
    "/chats/": {
      "get": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "messages"
        ],
        "summary": "Get all Chats",
        "operationId": "getAllChats",
        "responses": {
          "200": {
            "description": "Object found and returned",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Chat"
              }
            }
          },
          "400": {
            "description": "Invalid parameter input was passed",
            "schema": {
              "$ref": "#/definitions/InvalidParameterInput"
            }
          }
        }
      }
    },
    "/chats/{chatID}/messages": {
      "get": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "messages"
        ],
        "summary": "Add a new message",
        "operationId": "getAllMessagesForChat",
        "responses": {
          "200": {
            "description": "Object found and returned",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Message"
              }
            }
          },
          "400": {
            "description": "Invalid parameter input was passed",
            "schema": {
              "$ref": "#/definitions/InvalidParameterInput"
            }
          }
        }
      },
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "messages"
        ],
        "summary": "Add a new message",
        "operationId": "createNewMessage",
        "parameters": [
          {
            "description": "Message that needs to be added",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Message"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Object found and returned",
            "schema": {
              "$ref": "#/definitions/Message"
            }
          },
          "400": {
            "description": "Invalid parameter input was passed",
            "schema": {
              "$ref": "#/definitions/InvalidParameterInput"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "name": "chatID",
          "in": "path",
          "required": true
        }
      ]
    },
    "/chats/{chatID}/messages/{id}": {
      "get": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "messages"
        ],
        "summary": "Display a message",
        "operationId": "getMessageById",
        "responses": {
          "200": {
            "description": "Object found and returned",
            "schema": {
              "$ref": "#/definitions/Message"
            }
          },
          "400": {
            "description": "Invalid parameter input was passed",
            "schema": {
              "$ref": "#/definitions/InvalidParameterInput"
            }
          }
        }
      },
      "delete": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "messages"
        ],
        "summary": "Delete a message",
        "operationId": "deleteMessageById",
        "responses": {
          "204": {
            "description": "Removed; No response."
          },
          "400": {
            "description": "Invalid parameter input was passed",
            "schema": {
              "$ref": "#/definitions/InvalidParameterInput"
            }
          }
        }
      },
      "patch": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "messages"
        ],
        "summary": "Update a message",
        "operationId": "updateMessageById",
        "parameters": [
          {
            "description": "New parameters of the message",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Message"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "Accepted; No response."
          },
          "400": {
            "description": "Invalid parameter input was passed",
            "schema": {
              "$ref": "#/definitions/InvalidParameterInput"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "name": "chatID",
          "in": "path",
          "required": true
        },
        {
          "type": "string",
          "name": "id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/feed": {
      "get": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "offerings"
        ],
        "summary": "Display a feed of nearby offerings",
        "operationId": "getFeed",
        "parameters": [
          {
            "type": "string",
            "name": "location",
            "in": "query",
            "required": true
          },
          {
            "type": "number",
            "description": "Distance in Meters",
            "name": "distance",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Object found and returned",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Offering"
              }
            }
          },
          "400": {
            "description": "Invalid parameter input was passed",
            "schema": {
              "$ref": "#/definitions/InvalidParameterInput"
            }
          }
        }
      }
    },
    "/healthcheck": {
      "get": {
        "security": [],
        "produces": [
          "application/json"
        ],
        "tags": [
          "health"
        ],
        "summary": "Check Server status",
        "operationId": "healthcheckGet",
        "responses": {
          "200": {
            "description": "Server is healthy"
          },
          "503": {
            "description": "Server is unhealthy",
            "schema": {
              "$ref": "#/definitions/ErrorModel"
            }
          }
        }
      }
    },
    "/offerings": {
      "get": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "offerings"
        ],
        "summary": "Display a feed of nearby offerings",
        "operationId": "getOfferings",
        "parameters": [
          {
            "enum": [
              "owned",
              "requested"
            ],
            "type": "string",
            "description": "Filteres offerings by owned or requested",
            "name": "filter",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Object found and returned",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Offering"
              }
            }
          },
          "400": {
            "description": "Invalid parameter input was passed",
            "schema": {
              "$ref": "#/definitions/InvalidParameterInput"
            }
          }
        }
      },
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "offerings"
        ],
        "summary": "Add a new offering",
        "operationId": "createNewOffering",
        "parameters": [
          {
            "description": "Offering that needs to be added",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Offering"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Object found and returned",
            "schema": {
              "$ref": "#/definitions/Offering"
            }
          },
          "400": {
            "description": "Invalid parameter input was passed",
            "schema": {
              "$ref": "#/definitions/InvalidParameterInput"
            }
          }
        }
      }
    },
    "/offerings/{id}": {
      "get": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "offerings"
        ],
        "summary": "Display an offering",
        "operationId": "getOfferingById",
        "responses": {
          "200": {
            "description": "Object found and returned",
            "schema": {
              "$ref": "#/definitions/Offering"
            }
          },
          "400": {
            "description": "Invalid parameter input was passed",
            "schema": {
              "$ref": "#/definitions/InvalidParameterInput"
            }
          }
        }
      },
      "delete": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "offerings"
        ],
        "summary": "Delete an offering",
        "operationId": "deleteOfferingById",
        "responses": {
          "204": {
            "description": "Removed; No response."
          },
          "400": {
            "description": "Invalid parameter input was passed",
            "schema": {
              "$ref": "#/definitions/InvalidParameterInput"
            }
          }
        }
      },
      "patch": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "offerings"
        ],
        "summary": "Update an offering",
        "operationId": "updateOfferingById",
        "parameters": [
          {
            "description": "New parameters of the offering",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Offering"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "Accepted; No response."
          },
          "400": {
            "description": "Invalid parameter input was passed",
            "schema": {
              "$ref": "#/definitions/InvalidParameterInput"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "name": "id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/offerings/{id}/chats": {
      "get": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "offerings",
          "messages"
        ],
        "summary": "Display a user",
        "operationId": "getAllChatsForOffering",
        "responses": {
          "200": {
            "description": "Object found and returned",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Chat"
              }
            }
          },
          "400": {
            "description": "Invalid parameter input was passed",
            "schema": {
              "$ref": "#/definitions/InvalidParameterInput"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "name": "id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/users": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "users"
        ],
        "summary": "Add a new user",
        "operationId": "createNewUser",
        "parameters": [
          {
            "description": "User that needs to be added",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/User"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Object found and returned",
            "schema": {
              "$ref": "#/definitions/User"
            }
          },
          "400": {
            "description": "Invalid parameter input was passed",
            "schema": {
              "$ref": "#/definitions/InvalidParameterInput"
            }
          }
        }
      }
    },
    "/users/{id}": {
      "get": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "users"
        ],
        "summary": "Display a user",
        "operationId": "getUserById",
        "responses": {
          "200": {
            "description": "Object found and returned",
            "schema": {
              "$ref": "#/definitions/User"
            }
          },
          "400": {
            "description": "Invalid parameter input was passed",
            "schema": {
              "$ref": "#/definitions/InvalidParameterInput"
            }
          }
        }
      },
      "delete": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "users"
        ],
        "summary": "Delete a users",
        "operationId": "deleteUserById",
        "responses": {
          "204": {
            "description": "Removed; No response."
          },
          "400": {
            "description": "Invalid parameter input was passed",
            "schema": {
              "$ref": "#/definitions/InvalidParameterInput"
            }
          }
        }
      },
      "patch": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "users"
        ],
        "summary": "Update a user",
        "operationId": "updateUserById",
        "parameters": [
          {
            "description": "New parameters of the User",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/User"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "Accepted; No response."
          },
          "400": {
            "description": "Invalid parameter input was passed",
            "schema": {
              "$ref": "#/definitions/InvalidParameterInput"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "name": "id",
          "in": "path",
          "required": true
        }
      ]
    }
  },
  "definitions": {
    "Chat": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "offering-id": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "partner": {
          "$ref": "#/definitions/UserShort"
        }
      }
    },
    "ErrorModel": {
      "required": [
        "code",
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int32"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "InvalidParameterInput": {
      "type": "object",
      "required": [
        "attribute",
        "message"
      ],
      "properties": {
        "attribute": {
          "type": "string"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "Message": {
      "type": "object",
      "properties": {
        "content": {
          "type": "string"
        },
        "from": {
          "$ref": "#/definitions/UserShort"
        },
        "time": {
          "type": "string",
          "format": "date-time"
        }
      },
      "xml": {
        "name": "Message"
      }
    },
    "Offering": {
      "type": "object",
      "properties": {
        "avatar-url": {
          "type": "string"
        },
        "best-by-date": {
          "type": "string",
          "format": "date"
        },
        "creator-id": {
          "type": "string"
        },
        "header": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "location": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "requested-by": {
          "type": "integer",
          "format": "int64"
        },
        "time": {
          "type": "string",
          "format": "date-time"
        }
      },
      "xml": {
        "name": "Offering"
      }
    },
    "Principal": {
      "type": "object",
      "properties": {
        "email": {
          "type": "string"
        },
        "userid": {
          "type": "string"
        },
        "username": {
          "type": "string"
        }
      }
    },
    "User": {
      "type": "object",
      "properties": {
        "address": {
          "$ref": "#/definitions/userAddress"
        },
        "avatar-id": {
          "type": "string"
        },
        "background-id": {
          "type": "string"
        },
        "badges": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "description": {
          "type": "string"
        },
        "email": {
          "type": "string",
          "format": "email"
        },
        "firstname": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "lastname": {
          "type": "string"
        },
        "phone": {
          "type": "string",
          "format": "phone"
        }
      },
      "xml": {
        "name": "user"
      },
      "example": {
        "address": {
          "city": "Musterstadt",
          "number": 1337,
          "street": "Musterstraße",
          "zip": 42069
        },
        "avatar-id": "",
        "background-id": "",
        "badges": [
          true,
          false,
          true,
          true,
          true,
          false,
          false,
          true,
          false
        ],
        "description": "I save the wrap and the world",
        "email": "apiteam@swagger.io",
        "firstname": "Marty",
        "id": "5",
        "lastname": "McFlfy",
        "phone": "202-555-0191"
      }
    },
    "UserShort": {
      "type": "object",
      "properties": {
        "avatar-id": {
          "type": "string"
        },
        "firstname": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "lastname": {
          "type": "string"
        }
      },
      "xml": {
        "name": "user"
      },
      "example": {
        "avatar-id": "",
        "firstname": "Marty",
        "id": "5",
        "lastname": "McFlfy"
      }
    },
    "userAddress": {
      "type": "object",
      "properties": {
        "city": {
          "type": "string"
        },
        "number": {
          "type": "string"
        },
        "street": {
          "type": "string"
        },
        "zip": {
          "type": "integer",
          "format": "int64"
        }
      },
      "x-go-gen-location": "models"
    }
  },
  "responses": {
    "ErrorResponse": {
      "description": "Generic Error",
      "schema": {
        "$ref": "#/definitions/ErrorModel"
      }
    },
    "InvalidParameterInput": {
      "description": "Invalid parameter input was passed",
      "schema": {
        "$ref": "#/definitions/InvalidParameterInput"
      }
    },
    "NotFound": {
      "description": "The specified resource was not found",
      "schema": {
        "$ref": "#/definitions/ErrorModel"
      }
    },
    "Unauthorized": {
      "description": "Unauthorized",
      "schema": {
        "$ref": "#/definitions/ErrorModel"
      }
    },
    "Unhealthy": {
      "description": "Server is unhealthy",
      "schema": {
        "$ref": "#/definitions/ErrorModel"
      }
    }
  },
  "securityDefinitions": {
    "bearer": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header"
    }
  },
  "security": [
    {
      "bearer": []
    }
  ],
  "tags": [
    {
      "description": "Management of users",
      "name": "users"
    },
    {
      "description": "Management of offered food items",
      "name": "offerings"
    },
    {
      "description": "Operations about users",
      "name": "messages"
    },
    {
      "description": "Operation regarding helath of application",
      "name": "health"
    }
  ]
}`))
}
