// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "denn nur lebendiges food tut gut",
    "title": "Savood",
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version": "1.0"
  },
  "basePath": "/v2/",
  "paths": {
    "/chats/": {
      "get": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "messages"
        ],
        "summary": "Get all Chats",
        "operationId": "getAllChats",
        "responses": {
          "200": {
            "description": "Object found and returned",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Chat"
              }
            }
          },
          "400": {
            "$ref": "#/responses/InvalidParameterInput"
          }
        }
      }
    },
    "/chats/{chatID}/messages": {
      "get": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "messages"
        ],
        "summary": "Add a new message",
        "operationId": "getAllMessagesForChat",
        "responses": {
          "200": {
            "description": "Object found and returned",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Message"
              }
            }
          },
          "400": {
            "$ref": "#/responses/InvalidParameterInput"
          }
        }
      },
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "messages"
        ],
        "summary": "Add a new message",
        "operationId": "createNewMessage",
        "parameters": [
          {
            "description": "Message that needs to be added",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Message"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Object found and returned",
            "schema": {
              "$ref": "#/definitions/Message"
            }
          },
          "400": {
            "$ref": "#/responses/InvalidParameterInput"
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "name": "chatID",
          "in": "path",
          "required": true
        }
      ]
    },
    "/chats/{chatID}/messages/{id}": {
      "get": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "messages"
        ],
        "summary": "Display a message",
        "operationId": "getMessageById",
        "responses": {
          "200": {
            "description": "Object found and returned",
            "schema": {
              "$ref": "#/definitions/Message"
            }
          },
          "400": {
            "$ref": "#/responses/InvalidParameterInput"
          }
        }
      },
      "delete": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "messages"
        ],
        "summary": "Delete a message",
        "operationId": "deleteMessageById",
        "responses": {
          "204": {
            "description": "Removed; No response."
          },
          "400": {
            "$ref": "#/responses/InvalidParameterInput"
          }
        }
      },
      "patch": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "messages"
        ],
        "summary": "Update a message",
        "operationId": "updateMessageById",
        "parameters": [
          {
            "description": "New parameters of the message",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Message"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "Accepted; No response."
          },
          "400": {
            "$ref": "#/responses/InvalidParameterInput"
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "name": "chatID",
          "in": "path",
          "required": true
        },
        {
          "type": "string",
          "name": "id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/feed": {
      "get": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "offerings"
        ],
        "summary": "Display a feed of nearby offerings",
        "operationId": "getFeed",
        "parameters": [
          {
            "type": "number",
            "description": "Latitude",
            "name": "lat",
            "in": "query",
            "required": true
          },
          {
            "type": "number",
            "description": "Longitude",
            "name": "lon",
            "in": "query",
            "required": true
          },
          {
            "type": "number",
            "description": "Distance in Meters",
            "name": "distance",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Object found and returned",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Offering"
              }
            }
          },
          "400": {
            "$ref": "#/responses/InvalidParameterInput"
          },
          "500": {
            "$ref": "#/responses/ErrorResponse"
          }
        }
      }
    },
    "/healthcheck": {
      "get": {
        "security": [],
        "produces": [
          "application/json"
        ],
        "tags": [
          "health"
        ],
        "summary": "Check Server status",
        "operationId": "healthcheckGet",
        "responses": {
          "200": {
            "description": "Server is healthy"
          },
          "503": {
            "$ref": "#/responses/Unhealthy"
          }
        }
      }
    },
    "/offerings": {
      "get": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "offerings"
        ],
        "summary": "Display owned or requested offerings",
        "operationId": "getOfferings",
        "parameters": [
          {
            "enum": [
              "owned",
              "requested"
            ],
            "type": "string",
            "description": "Filteres offerings by owned or requested",
            "name": "filter",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Object found and returned",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Offering"
              }
            }
          },
          "400": {
            "$ref": "#/responses/InvalidParameterInput"
          },
          "500": {
            "$ref": "#/responses/ErrorResponse"
          }
        }
      },
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "offerings"
        ],
        "summary": "Add a new offering",
        "operationId": "createNewOffering",
        "parameters": [
          {
            "description": "Offering that needs to be added",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Offering"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Object found and returned",
            "schema": {
              "$ref": "#/definitions/Offering"
            }
          },
          "400": {
            "$ref": "#/responses/InvalidParameterInput"
          },
          "403": {
            "$ref": "#/responses/Unauthorized"
          },
          "500": {
            "$ref": "#/responses/ErrorResponse"
          }
        }
      }
    },
    "/offerings/{id}": {
      "get": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "offerings"
        ],
        "summary": "Display an offering",
        "operationId": "getOfferingById",
        "responses": {
          "200": {
            "description": "Object found and returned",
            "schema": {
              "$ref": "#/definitions/Offering"
            }
          },
          "400": {
            "$ref": "#/responses/InvalidParameterInput"
          },
          "404": {
            "$ref": "#/responses/NotFound"
          },
          "500": {
            "$ref": "#/responses/ErrorResponse"
          }
        }
      },
      "delete": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "offerings"
        ],
        "summary": "Delete an offering",
        "operationId": "deleteOfferingById",
        "responses": {
          "204": {
            "description": "Removed; No response."
          },
          "400": {
            "$ref": "#/responses/InvalidParameterInput"
          },
          "403": {
            "$ref": "#/responses/ErrorResponse"
          },
          "500": {
            "$ref": "#/responses/ErrorResponse"
          }
        }
      },
      "patch": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "offerings"
        ],
        "summary": "Update an offering",
        "operationId": "updateOfferingById",
        "parameters": [
          {
            "description": "New parameters of the offering",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Offering"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "Accepted; No response."
          },
          "400": {
            "$ref": "#/responses/InvalidParameterInput"
          },
          "403": {
            "$ref": "#/responses/ErrorResponse"
          },
          "404": {
            "$ref": "#/responses/NotFound"
          },
          "500": {
            "$ref": "#/responses/ErrorResponse"
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "name": "id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/offerings/{id}/chats": {
      "get": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "offerings",
          "messages"
        ],
        "summary": "Display a user",
        "operationId": "getAllChatsForOffering",
        "responses": {
          "200": {
            "description": "Object found and returned",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Chat"
              }
            }
          },
          "400": {
            "$ref": "#/responses/InvalidParameterInput"
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "name": "id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/offerings/{id}/image.jpeg": {
      "get": {
        "produces": [
          "image/jpeg",
          "application/json"
        ],
        "tags": [
          "offerings",
          "image"
        ],
        "summary": "Gets the avatar image.",
        "parameters": [
          {
            "type": "number",
            "description": "If either width or height is set to 0, it will be set to an aspect ratio preserving value.",
            "name": "height",
            "in": "query"
          },
          {
            "type": "number",
            "description": "If either width or height is set to 0, it will be set to an aspect ratio preserving value.",
            "name": "width",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "file"
            }
          },
          "404": {
            "$ref": "#/responses/NotFound"
          },
          "500": {
            "$ref": "#/responses/ErrorResponse"
          }
        }
      },
      "post": {
        "consumes": [
          "multipart/form-data"
        ],
        "tags": [
          "offerings",
          "image"
        ],
        "summary": "Uploads avatar image.",
        "parameters": [
          {
            "type": "file",
            "description": "The file to upload.",
            "name": "upfile",
            "in": "formData"
          }
        ],
        "responses": {
          "204": {
            "description": "Accepted; No response."
          },
          "400": {
            "$ref": "#/responses/InvalidParameterInput"
          },
          "403": {
            "$ref": "#/responses/Unauthorized"
          },
          "500": {
            "$ref": "#/responses/ErrorResponse"
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "name": "id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/placeSavood": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "rpc-calls",
          "offerings"
        ],
        "summary": "Places a savood on an offering",
        "operationId": "placeSavood",
        "parameters": [
          {
            "type": "string",
            "description": "The offering ID on which the savood should be placed.",
            "name": "offeringId",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Savood is placed",
            "schema": {
              "$ref": "#/definitions/SuccessObject"
            }
          },
          "400": {
            "$ref": "#/responses/InvalidParameterInput"
          },
          "403": {
            "$ref": "#/responses/ErrorResponse"
          },
          "404": {
            "$ref": "#/responses/NotFound"
          },
          "500": {
            "$ref": "#/responses/ErrorResponse"
          }
        }
      }
    },
    "/unSavood": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "rpc-calls",
          "offerings"
        ],
        "summary": "Places a savood on an offering",
        "operationId": "unSavood",
        "parameters": [
          {
            "type": "string",
            "description": "The offering ID on which the savood should be placed.",
            "name": "offeringId",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Savood is deleted",
            "schema": {
              "$ref": "#/definitions/SuccessObject"
            }
          },
          "400": {
            "$ref": "#/responses/InvalidParameterInput"
          },
          "403": {
            "$ref": "#/responses/ErrorResponse"
          },
          "404": {
            "$ref": "#/responses/NotFound"
          },
          "500": {
            "$ref": "#/responses/ErrorResponse"
          }
        }
      }
    },
    "/users": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "users"
        ],
        "summary": "Add a new user",
        "operationId": "createNewUser",
        "parameters": [
          {
            "description": "User that needs to be added",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/User"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Object found and returned",
            "schema": {
              "$ref": "#/definitions/User"
            }
          },
          "400": {
            "$ref": "#/responses/InvalidParameterInput"
          }
        }
      }
    },
    "/users/{id}": {
      "get": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "users"
        ],
        "summary": "Display a user",
        "operationId": "getUserById",
        "responses": {
          "200": {
            "description": "Object found and returned",
            "schema": {
              "$ref": "#/definitions/User"
            }
          },
          "400": {
            "$ref": "#/responses/InvalidParameterInput"
          }
        }
      },
      "delete": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "users"
        ],
        "summary": "Delete a users",
        "operationId": "deleteUserById",
        "responses": {
          "204": {
            "description": "Removed; No response."
          },
          "400": {
            "$ref": "#/responses/InvalidParameterInput"
          }
        }
      },
      "patch": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "users"
        ],
        "summary": "Update a user",
        "operationId": "updateUserById",
        "parameters": [
          {
            "description": "New parameters of the User",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/User"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "Accepted; No response."
          },
          "400": {
            "$ref": "#/responses/InvalidParameterInput"
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "name": "id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/users/{id}/backgroundimage.jpeg": {
      "get": {
        "produces": [
          "image/jpeg",
          "application/json"
        ],
        "tags": [
          "users",
          "image"
        ],
        "summary": "Gets the avatar image.",
        "parameters": [
          {
            "type": "number",
            "description": "If either width or height is set to 0, it will be set to an aspect ratio preserving value.",
            "name": "height",
            "in": "query"
          },
          {
            "type": "number",
            "description": "If either width or height is set to 0, it will be set to an aspect ratio preserving value.",
            "name": "width",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "file"
            }
          },
          "404": {
            "$ref": "#/responses/NotFound"
          },
          "500": {
            "$ref": "#/responses/ErrorResponse"
          }
        }
      },
      "post": {
        "consumes": [
          "multipart/form-data"
        ],
        "tags": [
          "users",
          "image"
        ],
        "summary": "Uploads avatar image.",
        "parameters": [
          {
            "type": "file",
            "description": "The file to upload.",
            "name": "upfile",
            "in": "formData"
          }
        ],
        "responses": {
          "204": {
            "description": "Accepted; No response."
          },
          "400": {
            "$ref": "#/responses/InvalidParameterInput"
          },
          "403": {
            "$ref": "#/responses/Unauthorized"
          },
          "500": {
            "$ref": "#/responses/ErrorResponse"
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "name": "id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/users/{id}/image.jpeg": {
      "get": {
        "produces": [
          "image/jpeg",
          "application/json"
        ],
        "tags": [
          "users",
          "image"
        ],
        "summary": "Gets the avatar image.",
        "parameters": [
          {
            "type": "number",
            "description": "If either width or height is set to 0, it will be set to an aspect ratio preserving value.",
            "name": "height",
            "in": "query"
          },
          {
            "type": "number",
            "description": "If either width or height is set to 0, it will be set to an aspect ratio preserving value.",
            "name": "width",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "file"
            }
          },
          "404": {
            "$ref": "#/responses/NotFound"
          },
          "500": {
            "$ref": "#/responses/ErrorResponse"
          }
        }
      },
      "post": {
        "consumes": [
          "multipart/form-data"
        ],
        "tags": [
          "users",
          "image"
        ],
        "summary": "Uploads avatar image.",
        "parameters": [
          {
            "type": "file",
            "description": "The file to upload.",
            "name": "upfile",
            "in": "formData"
          }
        ],
        "responses": {
          "204": {
            "description": "Accepted; No response."
          },
          "400": {
            "$ref": "#/responses/InvalidParameterInput"
          },
          "403": {
            "$ref": "#/responses/Unauthorized"
          },
          "500": {
            "$ref": "#/responses/ErrorResponse"
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "name": "id",
          "in": "path",
          "required": true
        }
      ]
    }
  },
  "definitions": {
    "Address": {
      "type": "object",
      "properties": {
        "city": {
          "type": "string"
        },
        "number": {
          "type": "string"
        },
        "street": {
          "type": "string"
        },
        "zip": {
          "type": "string"
        }
      }
    },
    "Chat": {
      "type": "object",
      "properties": {
        "_id": {
          "type": "string"
        },
        "offeringId": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "partner": {
          "$ref": "#/definitions/UserShort"
        }
      },
      "example": {
        "_id": "17",
        "offeringId": [
          1,
          2,
          3,
          4,
          5
        ],
        "partner": {
          "_id": "5",
          "firstname": "Marty",
          "lastname": "McFlfy"
        }
      }
    },
    "ErrorModel": {
      "required": [
        "code",
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int32"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "InvalidParameterInput": {
      "type": "object",
      "required": [
        "attribute",
        "message"
      ],
      "properties": {
        "attribute": {
          "type": "string"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "Message": {
      "type": "object",
      "properties": {
        "content": {
          "type": "string"
        },
        "from": {
          "$ref": "#/definitions/UserShort"
        },
        "time": {
          "type": "string",
          "format": "date-time"
        }
      },
      "xml": {
        "name": "Message"
      }
    },
    "Offering": {
      "type": "object",
      "properties": {
        "_id": {
          "type": "string"
        },
        "address": {
          "$ref": "#/definitions/Address"
        },
        "best-by-date": {
          "type": "string",
          "format": "date"
        },
        "creator": {
          "$ref": "#/definitions/UserShort"
        },
        "description": {
          "type": "string"
        },
        "location": {
          "type": "object",
          "properties": {
            "coordinates": {
              "description": "longitude then latidue as floats",
              "type": "array",
              "items": {
                "type": "number"
              }
            },
            "type": {
              "type": "string"
            }
          }
        },
        "name": {
          "type": "string"
        },
        "requested-by": {
          "type": "integer",
          "format": "int64"
        },
        "savooded": {
          "type": "boolean"
        },
        "time": {
          "type": "string",
          "format": "date-time"
        }
      },
      "xml": {
        "name": "Offering"
      },
      "example": {
        "_id": "123",
        "address": {
          "city": "Musterstadt",
          "number": "1337",
          "street": "Musterstraße",
          "zip": "42069"
        },
        "best-by-date": "2018-06-21",
        "creator": {
          "_id": "5",
          "firstname": "Marty",
          "lastname": "McFlfy"
        },
        "description": "Die Lagen hier so rum, kp mehr von wann, aber was solls. ich brauche Sie nicht mehr. Also nur zu Savooded mich ihr Jünger",
        "location": {
          "coordinates": [
            50.5636277,
            9.6711443
          ]
        },
        "name": "Normale Kartoffeln",
        "requested-by": 12,
        "savooded": true,
        "time": "2018-06-21T13:55:58.380Z"
      }
    },
    "Principal": {
      "type": "object",
      "properties": {
        "email": {
          "type": "string"
        },
        "userid": {
          "type": "string"
        }
      }
    },
    "SuccessObject": {
      "type": "object",
      "properties": {
        "success": {
          "type": "boolean"
        }
      }
    },
    "User": {
      "type": "object",
      "properties": {
        "_id": {
          "type": "string"
        },
        "address": {
          "$ref": "#/definitions/Address"
        },
        "badges": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "description": {
          "type": "string"
        },
        "email": {
          "type": "string",
          "format": "email"
        },
        "firstname": {
          "type": "string"
        },
        "lastname": {
          "type": "string"
        },
        "phone": {
          "type": "string",
          "format": "phone"
        }
      },
      "xml": {
        "name": "user"
      },
      "example": {
        "_id": "5",
        "address": {
          "city": "Musterstadt",
          "number": "1337",
          "street": "Musterstraße",
          "zip": "42069"
        },
        "avatarId": "",
        "backgroundId": "",
        "badges": [
          "SAVOOD_1",
          "SAVOOD_5",
          "SAVOOD_10",
          "MESSAGE_1"
        ],
        "description": "I save the wrap and the world",
        "email": "apiteam@swagger.io",
        "firstname": "Marty",
        "lastname": "McFlfy",
        "phone": "202-555-0191"
      }
    },
    "UserShort": {
      "type": "object",
      "properties": {
        "_id": {
          "type": "string"
        },
        "badges": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "firstname": {
          "type": "string"
        },
        "lastname": {
          "type": "string"
        }
      },
      "xml": {
        "name": "user"
      },
      "example": {
        "_id": "5",
        "badges": [
          "SAVOOD_1",
          "SAVOOD_5",
          "SAVOOD_10",
          "MESSAGE_1"
        ],
        "firstname": "Marty",
        "lastname": "McFlfy"
      }
    }
  },
  "responses": {
    "ErrorResponse": {
      "description": "Generic Error",
      "schema": {
        "$ref": "#/definitions/ErrorModel"
      }
    },
    "InvalidParameterInput": {
      "description": "Invalid parameter input was passed",
      "schema": {
        "$ref": "#/definitions/InvalidParameterInput"
      }
    },
    "NotFound": {
      "description": "The specified resource was not found",
      "schema": {
        "$ref": "#/definitions/ErrorModel"
      }
    },
    "Unauthorized": {
      "description": "Unauthorized",
      "schema": {
        "$ref": "#/definitions/ErrorModel"
      }
    },
    "Unhealthy": {
      "description": "Server is unhealthy",
      "schema": {
        "$ref": "#/definitions/ErrorModel"
      }
    }
  },
  "securityDefinitions": {
    "bearer": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header"
    }
  },
  "security": [
    {
      "bearer": []
    }
  ],
  "tags": [
    {
      "description": "Management of users",
      "name": "users"
    },
    {
      "description": "Management of offered food items",
      "name": "offerings"
    },
    {
      "description": "Operations about users",
      "name": "messages"
    },
    {
      "description": "Operation regarding helath of application",
      "name": "health"
    }
  ]
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "denn nur lebendiges food tut gut",
    "title": "Savood",
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version": "1.0"
  },
  "basePath": "/v2/",
  "paths": {
    "/chats/": {
      "get": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "messages"
        ],
        "summary": "Get all Chats",
        "operationId": "getAllChats",
        "responses": {
          "200": {
            "description": "Object found and returned",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Chat"
              }
            }
          },
          "400": {
            "description": "Invalid parameter input was passed",
            "schema": {
              "$ref": "#/definitions/InvalidParameterInput"
            }
          }
        }
      }
    },
    "/chats/{chatID}/messages": {
      "get": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "messages"
        ],
        "summary": "Add a new message",
        "operationId": "getAllMessagesForChat",
        "responses": {
          "200": {
            "description": "Object found and returned",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Message"
              }
            }
          },
          "400": {
            "description": "Invalid parameter input was passed",
            "schema": {
              "$ref": "#/definitions/InvalidParameterInput"
            }
          }
        }
      },
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "messages"
        ],
        "summary": "Add a new message",
        "operationId": "createNewMessage",
        "parameters": [
          {
            "description": "Message that needs to be added",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Message"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Object found and returned",
            "schema": {
              "$ref": "#/definitions/Message"
            }
          },
          "400": {
            "description": "Invalid parameter input was passed",
            "schema": {
              "$ref": "#/definitions/InvalidParameterInput"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "name": "chatID",
          "in": "path",
          "required": true
        }
      ]
    },
    "/chats/{chatID}/messages/{id}": {
      "get": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "messages"
        ],
        "summary": "Display a message",
        "operationId": "getMessageById",
        "responses": {
          "200": {
            "description": "Object found and returned",
            "schema": {
              "$ref": "#/definitions/Message"
            }
          },
          "400": {
            "description": "Invalid parameter input was passed",
            "schema": {
              "$ref": "#/definitions/InvalidParameterInput"
            }
          }
        }
      },
      "delete": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "messages"
        ],
        "summary": "Delete a message",
        "operationId": "deleteMessageById",
        "responses": {
          "204": {
            "description": "Removed; No response."
          },
          "400": {
            "description": "Invalid parameter input was passed",
            "schema": {
              "$ref": "#/definitions/InvalidParameterInput"
            }
          }
        }
      },
      "patch": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "messages"
        ],
        "summary": "Update a message",
        "operationId": "updateMessageById",
        "parameters": [
          {
            "description": "New parameters of the message",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Message"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "Accepted; No response."
          },
          "400": {
            "description": "Invalid parameter input was passed",
            "schema": {
              "$ref": "#/definitions/InvalidParameterInput"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "name": "chatID",
          "in": "path",
          "required": true
        },
        {
          "type": "string",
          "name": "id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/feed": {
      "get": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "offerings"
        ],
        "summary": "Display a feed of nearby offerings",
        "operationId": "getFeed",
        "parameters": [
          {
            "type": "number",
            "description": "Latitude",
            "name": "lat",
            "in": "query",
            "required": true
          },
          {
            "type": "number",
            "description": "Longitude",
            "name": "lon",
            "in": "query",
            "required": true
          },
          {
            "type": "number",
            "description": "Distance in Meters",
            "name": "distance",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Object found and returned",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Offering"
              }
            }
          },
          "400": {
            "description": "Invalid parameter input was passed",
            "schema": {
              "$ref": "#/definitions/InvalidParameterInput"
            }
          },
          "500": {
            "description": "Generic Error",
            "schema": {
              "$ref": "#/definitions/ErrorModel"
            }
          }
        }
      }
    },
    "/healthcheck": {
      "get": {
        "security": [],
        "produces": [
          "application/json"
        ],
        "tags": [
          "health"
        ],
        "summary": "Check Server status",
        "operationId": "healthcheckGet",
        "responses": {
          "200": {
            "description": "Server is healthy"
          },
          "503": {
            "description": "Server is unhealthy",
            "schema": {
              "$ref": "#/definitions/ErrorModel"
            }
          }
        }
      }
    },
    "/offerings": {
      "get": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "offerings"
        ],
        "summary": "Display owned or requested offerings",
        "operationId": "getOfferings",
        "parameters": [
          {
            "enum": [
              "owned",
              "requested"
            ],
            "type": "string",
            "description": "Filteres offerings by owned or requested",
            "name": "filter",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Object found and returned",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Offering"
              }
            }
          },
          "400": {
            "description": "Invalid parameter input was passed",
            "schema": {
              "$ref": "#/definitions/InvalidParameterInput"
            }
          },
          "500": {
            "description": "Generic Error",
            "schema": {
              "$ref": "#/definitions/ErrorModel"
            }
          }
        }
      },
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "offerings"
        ],
        "summary": "Add a new offering",
        "operationId": "createNewOffering",
        "parameters": [
          {
            "description": "Offering that needs to be added",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Offering"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Object found and returned",
            "schema": {
              "$ref": "#/definitions/Offering"
            }
          },
          "400": {
            "description": "Invalid parameter input was passed",
            "schema": {
              "$ref": "#/definitions/InvalidParameterInput"
            }
          },
          "403": {
            "description": "Unauthorized",
            "schema": {
              "$ref": "#/definitions/ErrorModel"
            }
          },
          "500": {
            "description": "Generic Error",
            "schema": {
              "$ref": "#/definitions/ErrorModel"
            }
          }
        }
      }
    },
    "/offerings/{id}": {
      "get": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "offerings"
        ],
        "summary": "Display an offering",
        "operationId": "getOfferingById",
        "responses": {
          "200": {
            "description": "Object found and returned",
            "schema": {
              "$ref": "#/definitions/Offering"
            }
          },
          "400": {
            "description": "Invalid parameter input was passed",
            "schema": {
              "$ref": "#/definitions/InvalidParameterInput"
            }
          },
          "404": {
            "description": "The specified resource was not found",
            "schema": {
              "$ref": "#/definitions/ErrorModel"
            }
          },
          "500": {
            "description": "Generic Error",
            "schema": {
              "$ref": "#/definitions/ErrorModel"
            }
          }
        }
      },
      "delete": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "offerings"
        ],
        "summary": "Delete an offering",
        "operationId": "deleteOfferingById",
        "responses": {
          "204": {
            "description": "Removed; No response."
          },
          "400": {
            "description": "Invalid parameter input was passed",
            "schema": {
              "$ref": "#/definitions/InvalidParameterInput"
            }
          },
          "403": {
            "description": "Generic Error",
            "schema": {
              "$ref": "#/definitions/ErrorModel"
            }
          },
          "500": {
            "description": "Generic Error",
            "schema": {
              "$ref": "#/definitions/ErrorModel"
            }
          }
        }
      },
      "patch": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "offerings"
        ],
        "summary": "Update an offering",
        "operationId": "updateOfferingById",
        "parameters": [
          {
            "description": "New parameters of the offering",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Offering"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "Accepted; No response."
          },
          "400": {
            "description": "Invalid parameter input was passed",
            "schema": {
              "$ref": "#/definitions/InvalidParameterInput"
            }
          },
          "403": {
            "description": "Generic Error",
            "schema": {
              "$ref": "#/definitions/ErrorModel"
            }
          },
          "404": {
            "description": "The specified resource was not found",
            "schema": {
              "$ref": "#/definitions/ErrorModel"
            }
          },
          "500": {
            "description": "Generic Error",
            "schema": {
              "$ref": "#/definitions/ErrorModel"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "name": "id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/offerings/{id}/chats": {
      "get": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "offerings",
          "messages"
        ],
        "summary": "Display a user",
        "operationId": "getAllChatsForOffering",
        "responses": {
          "200": {
            "description": "Object found and returned",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Chat"
              }
            }
          },
          "400": {
            "description": "Invalid parameter input was passed",
            "schema": {
              "$ref": "#/definitions/InvalidParameterInput"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "name": "id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/offerings/{id}/image.jpeg": {
      "get": {
        "produces": [
          "image/jpeg",
          "application/json"
        ],
        "tags": [
          "offerings",
          "image"
        ],
        "summary": "Gets the avatar image.",
        "parameters": [
          {
            "type": "number",
            "description": "If either width or height is set to 0, it will be set to an aspect ratio preserving value.",
            "name": "height",
            "in": "query"
          },
          {
            "type": "number",
            "description": "If either width or height is set to 0, it will be set to an aspect ratio preserving value.",
            "name": "width",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/getOfferingsIdImageJpegOKBody"
            }
          },
          "404": {
            "description": "The specified resource was not found",
            "schema": {
              "$ref": "#/definitions/ErrorModel"
            }
          },
          "500": {
            "description": "Generic Error",
            "schema": {
              "$ref": "#/definitions/ErrorModel"
            }
          }
        }
      },
      "post": {
        "consumes": [
          "multipart/form-data"
        ],
        "tags": [
          "offerings",
          "image"
        ],
        "summary": "Uploads avatar image.",
        "parameters": [
          {
            "type": "file",
            "description": "The file to upload.",
            "name": "upfile",
            "in": "formData"
          }
        ],
        "responses": {
          "204": {
            "description": "Accepted; No response."
          },
          "400": {
            "description": "Invalid parameter input was passed",
            "schema": {
              "$ref": "#/definitions/InvalidParameterInput"
            }
          },
          "403": {
            "description": "Unauthorized",
            "schema": {
              "$ref": "#/definitions/ErrorModel"
            }
          },
          "500": {
            "description": "Generic Error",
            "schema": {
              "$ref": "#/definitions/ErrorModel"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "name": "id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/placeSavood": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "rpc-calls",
          "offerings"
        ],
        "summary": "Places a savood on an offering",
        "operationId": "placeSavood",
        "parameters": [
          {
            "type": "string",
            "description": "The offering ID on which the savood should be placed.",
            "name": "offeringId",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Savood is placed",
            "schema": {
              "$ref": "#/definitions/SuccessObject"
            }
          },
          "400": {
            "description": "Invalid parameter input was passed",
            "schema": {
              "$ref": "#/definitions/InvalidParameterInput"
            }
          },
          "403": {
            "description": "Generic Error",
            "schema": {
              "$ref": "#/definitions/ErrorModel"
            }
          },
          "404": {
            "description": "The specified resource was not found",
            "schema": {
              "$ref": "#/definitions/ErrorModel"
            }
          },
          "500": {
            "description": "Generic Error",
            "schema": {
              "$ref": "#/definitions/ErrorModel"
            }
          }
        }
      }
    },
    "/unSavood": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "rpc-calls",
          "offerings"
        ],
        "summary": "Places a savood on an offering",
        "operationId": "unSavood",
        "parameters": [
          {
            "type": "string",
            "description": "The offering ID on which the savood should be placed.",
            "name": "offeringId",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Savood is deleted",
            "schema": {
              "$ref": "#/definitions/SuccessObject"
            }
          },
          "400": {
            "description": "Invalid parameter input was passed",
            "schema": {
              "$ref": "#/definitions/InvalidParameterInput"
            }
          },
          "403": {
            "description": "Generic Error",
            "schema": {
              "$ref": "#/definitions/ErrorModel"
            }
          },
          "404": {
            "description": "The specified resource was not found",
            "schema": {
              "$ref": "#/definitions/ErrorModel"
            }
          },
          "500": {
            "description": "Generic Error",
            "schema": {
              "$ref": "#/definitions/ErrorModel"
            }
          }
        }
      }
    },
    "/users": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "users"
        ],
        "summary": "Add a new user",
        "operationId": "createNewUser",
        "parameters": [
          {
            "description": "User that needs to be added",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/User"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Object found and returned",
            "schema": {
              "$ref": "#/definitions/User"
            }
          },
          "400": {
            "description": "Invalid parameter input was passed",
            "schema": {
              "$ref": "#/definitions/InvalidParameterInput"
            }
          }
        }
      }
    },
    "/users/{id}": {
      "get": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "users"
        ],
        "summary": "Display a user",
        "operationId": "getUserById",
        "responses": {
          "200": {
            "description": "Object found and returned",
            "schema": {
              "$ref": "#/definitions/User"
            }
          },
          "400": {
            "description": "Invalid parameter input was passed",
            "schema": {
              "$ref": "#/definitions/InvalidParameterInput"
            }
          }
        }
      },
      "delete": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "users"
        ],
        "summary": "Delete a users",
        "operationId": "deleteUserById",
        "responses": {
          "204": {
            "description": "Removed; No response."
          },
          "400": {
            "description": "Invalid parameter input was passed",
            "schema": {
              "$ref": "#/definitions/InvalidParameterInput"
            }
          }
        }
      },
      "patch": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "users"
        ],
        "summary": "Update a user",
        "operationId": "updateUserById",
        "parameters": [
          {
            "description": "New parameters of the User",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/User"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "Accepted; No response."
          },
          "400": {
            "description": "Invalid parameter input was passed",
            "schema": {
              "$ref": "#/definitions/InvalidParameterInput"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "name": "id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/users/{id}/backgroundimage.jpeg": {
      "get": {
        "produces": [
          "image/jpeg",
          "application/json"
        ],
        "tags": [
          "users",
          "image"
        ],
        "summary": "Gets the avatar image.",
        "parameters": [
          {
            "type": "number",
            "description": "If either width or height is set to 0, it will be set to an aspect ratio preserving value.",
            "name": "height",
            "in": "query"
          },
          {
            "type": "number",
            "description": "If either width or height is set to 0, it will be set to an aspect ratio preserving value.",
            "name": "width",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/getUsersIdBackgroundimageJpegOKBody"
            }
          },
          "404": {
            "description": "The specified resource was not found",
            "schema": {
              "$ref": "#/definitions/ErrorModel"
            }
          },
          "500": {
            "description": "Generic Error",
            "schema": {
              "$ref": "#/definitions/ErrorModel"
            }
          }
        }
      },
      "post": {
        "consumes": [
          "multipart/form-data"
        ],
        "tags": [
          "users",
          "image"
        ],
        "summary": "Uploads avatar image.",
        "parameters": [
          {
            "type": "file",
            "description": "The file to upload.",
            "name": "upfile",
            "in": "formData"
          }
        ],
        "responses": {
          "204": {
            "description": "Accepted; No response."
          },
          "400": {
            "description": "Invalid parameter input was passed",
            "schema": {
              "$ref": "#/definitions/InvalidParameterInput"
            }
          },
          "403": {
            "description": "Unauthorized",
            "schema": {
              "$ref": "#/definitions/ErrorModel"
            }
          },
          "500": {
            "description": "Generic Error",
            "schema": {
              "$ref": "#/definitions/ErrorModel"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "name": "id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/users/{id}/image.jpeg": {
      "get": {
        "produces": [
          "image/jpeg",
          "application/json"
        ],
        "tags": [
          "users",
          "image"
        ],
        "summary": "Gets the avatar image.",
        "parameters": [
          {
            "type": "number",
            "description": "If either width or height is set to 0, it will be set to an aspect ratio preserving value.",
            "name": "height",
            "in": "query"
          },
          {
            "type": "number",
            "description": "If either width or height is set to 0, it will be set to an aspect ratio preserving value.",
            "name": "width",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/getUsersIdImageJpegOKBody"
            }
          },
          "404": {
            "description": "The specified resource was not found",
            "schema": {
              "$ref": "#/definitions/ErrorModel"
            }
          },
          "500": {
            "description": "Generic Error",
            "schema": {
              "$ref": "#/definitions/ErrorModel"
            }
          }
        }
      },
      "post": {
        "consumes": [
          "multipart/form-data"
        ],
        "tags": [
          "users",
          "image"
        ],
        "summary": "Uploads avatar image.",
        "parameters": [
          {
            "type": "file",
            "description": "The file to upload.",
            "name": "upfile",
            "in": "formData"
          }
        ],
        "responses": {
          "204": {
            "description": "Accepted; No response."
          },
          "400": {
            "description": "Invalid parameter input was passed",
            "schema": {
              "$ref": "#/definitions/InvalidParameterInput"
            }
          },
          "403": {
            "description": "Unauthorized",
            "schema": {
              "$ref": "#/definitions/ErrorModel"
            }
          },
          "500": {
            "description": "Generic Error",
            "schema": {
              "$ref": "#/definitions/ErrorModel"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "name": "id",
          "in": "path",
          "required": true
        }
      ]
    }
  },
  "definitions": {
    "Address": {
      "type": "object",
      "properties": {
        "city": {
          "type": "string"
        },
        "number": {
          "type": "string"
        },
        "street": {
          "type": "string"
        },
        "zip": {
          "type": "string"
        }
      }
    },
    "Chat": {
      "type": "object",
      "properties": {
        "_id": {
          "type": "string"
        },
        "offeringId": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "partner": {
          "$ref": "#/definitions/UserShort"
        }
      },
      "example": {
        "_id": "17",
        "offeringId": [
          1,
          2,
          3,
          4,
          5
        ],
        "partner": {
          "_id": "5",
          "firstname": "Marty",
          "lastname": "McFlfy"
        }
      }
    },
    "ErrorModel": {
      "required": [
        "code",
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int32"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "InvalidParameterInput": {
      "type": "object",
      "required": [
        "attribute",
        "message"
      ],
      "properties": {
        "attribute": {
          "type": "string"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "Message": {
      "type": "object",
      "properties": {
        "content": {
          "type": "string"
        },
        "from": {
          "$ref": "#/definitions/UserShort"
        },
        "time": {
          "type": "string",
          "format": "date-time"
        }
      },
      "xml": {
        "name": "Message"
      }
    },
    "Offering": {
      "type": "object",
      "properties": {
        "_id": {
          "type": "string"
        },
        "address": {
          "$ref": "#/definitions/Address"
        },
        "best-by-date": {
          "type": "string",
          "format": "date"
        },
        "creator": {
          "$ref": "#/definitions/UserShort"
        },
        "description": {
          "type": "string"
        },
        "location": {
          "$ref": "#/definitions/offeringLocation"
        },
        "name": {
          "type": "string"
        },
        "requested-by": {
          "type": "integer",
          "format": "int64"
        },
        "savooded": {
          "type": "boolean"
        },
        "time": {
          "type": "string",
          "format": "date-time"
        }
      },
      "xml": {
        "name": "Offering"
      },
      "example": {
        "_id": "123",
        "address": {
          "city": "Musterstadt",
          "number": "1337",
          "street": "Musterstraße",
          "zip": "42069"
        },
        "best-by-date": "2018-06-21",
        "creator": {
          "_id": "5",
          "firstname": "Marty",
          "lastname": "McFlfy"
        },
        "description": "Die Lagen hier so rum, kp mehr von wann, aber was solls. ich brauche Sie nicht mehr. Also nur zu Savooded mich ihr Jünger",
        "location": {
          "coordinates": [
            50.5636277,
            9.6711443
          ]
        },
        "name": "Normale Kartoffeln",
        "requested-by": 12,
        "savooded": true,
        "time": "2018-06-21T13:55:58.380Z"
      }
    },
    "Principal": {
      "type": "object",
      "properties": {
        "email": {
          "type": "string"
        },
        "userid": {
          "type": "string"
        }
      }
    },
    "SuccessObject": {
      "type": "object",
      "properties": {
        "success": {
          "type": "boolean"
        }
      }
    },
    "User": {
      "type": "object",
      "properties": {
        "_id": {
          "type": "string"
        },
        "address": {
          "$ref": "#/definitions/Address"
        },
        "badges": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "description": {
          "type": "string"
        },
        "email": {
          "type": "string",
          "format": "email"
        },
        "firstname": {
          "type": "string"
        },
        "lastname": {
          "type": "string"
        },
        "phone": {
          "type": "string",
          "format": "phone"
        }
      },
      "xml": {
        "name": "user"
      },
      "example": {
        "_id": "5",
        "address": {
          "city": "Musterstadt",
          "number": "1337",
          "street": "Musterstraße",
          "zip": "42069"
        },
        "avatarId": "",
        "backgroundId": "",
        "badges": [
          "SAVOOD_1",
          "SAVOOD_5",
          "SAVOOD_10",
          "MESSAGE_1"
        ],
        "description": "I save the wrap and the world",
        "email": "apiteam@swagger.io",
        "firstname": "Marty",
        "lastname": "McFlfy",
        "phone": "202-555-0191"
      }
    },
    "UserShort": {
      "type": "object",
      "properties": {
        "_id": {
          "type": "string"
        },
        "badges": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "firstname": {
          "type": "string"
        },
        "lastname": {
          "type": "string"
        }
      },
      "xml": {
        "name": "user"
      },
      "example": {
        "_id": "5",
        "badges": [
          "SAVOOD_1",
          "SAVOOD_5",
          "SAVOOD_10",
          "MESSAGE_1"
        ],
        "firstname": "Marty",
        "lastname": "McFlfy"
      }
    },
    "getOfferingsIdImageJpegOKBody": {
      "type": "file",
      "x-go-gen-location": "operations"
    },
    "getUsersIdBackgroundimageJpegOKBody": {
      "type": "file",
      "x-go-gen-location": "operations"
    },
    "getUsersIdImageJpegOKBody": {
      "type": "file",
      "x-go-gen-location": "operations"
    },
    "offeringLocation": {
      "type": "object",
      "properties": {
        "coordinates": {
          "description": "longitude then latidue as floats",
          "type": "array",
          "items": {
            "type": "number"
          }
        },
        "type": {
          "type": "string"
        }
      },
      "x-go-gen-location": "models"
    }
  },
  "responses": {
    "ErrorResponse": {
      "description": "Generic Error",
      "schema": {
        "$ref": "#/definitions/ErrorModel"
      }
    },
    "InvalidParameterInput": {
      "description": "Invalid parameter input was passed",
      "schema": {
        "$ref": "#/definitions/InvalidParameterInput"
      }
    },
    "NotFound": {
      "description": "The specified resource was not found",
      "schema": {
        "$ref": "#/definitions/ErrorModel"
      }
    },
    "Unauthorized": {
      "description": "Unauthorized",
      "schema": {
        "$ref": "#/definitions/ErrorModel"
      }
    },
    "Unhealthy": {
      "description": "Server is unhealthy",
      "schema": {
        "$ref": "#/definitions/ErrorModel"
      }
    }
  },
  "securityDefinitions": {
    "bearer": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header"
    }
  },
  "security": [
    {
      "bearer": []
    }
  ],
  "tags": [
    {
      "description": "Management of users",
      "name": "users"
    },
    {
      "description": "Management of offered food items",
      "name": "offerings"
    },
    {
      "description": "Operations about users",
      "name": "messages"
    },
    {
      "description": "Operation regarding helath of application",
      "name": "health"
    }
  ]
}`))
}
