// Code generated by go-swagger; DO NOT EDIT.

package messages

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"

	models "git.dhbw.chd.cx/backend/models"
)

// NewCreateNewMessageParams creates a new CreateNewMessageParams object
// no default values defined in spec.
func NewCreateNewMessageParams() CreateNewMessageParams {

	return CreateNewMessageParams{}
}

// CreateNewMessageParams contains all the bound params for the create new message operation
// typically these are obtained from a http.Request
//
// swagger:parameters createNewMessage
type CreateNewMessageParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Message that needs to be added
	  Required: true
	  In: body
	*/
	Body *models.Message
	/*
	  Required: true
	  In: path
	*/
	ChatID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewCreateNewMessageParams() beforehand.
func (o *CreateNewMessageParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.Message
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("body", "body"))
			} else {
				res = append(res, errors.NewParseError("body", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Body = &body
			}
		}
	} else {
		res = append(res, errors.Required("body", "body"))
	}
	rChatID, rhkChatID, _ := route.Params.GetOK("chatID")
	if err := o.bindChatID(rChatID, rhkChatID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindChatID binds and validates parameter ChatID from path.
func (o *CreateNewMessageParams) bindChatID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.ChatID = raw

	return nil
}
