// Code generated by go-swagger; DO NOT EDIT.

package messages

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "git.dhbw.chd.cx/savood/backend/models"
)

// GetAllMessagesForChatOKCode is the HTTP code returned for type GetAllMessagesForChatOK
const GetAllMessagesForChatOKCode int = 200

/*GetAllMessagesForChatOK Object found and returned

swagger:response getAllMessagesForChatOK
*/
type GetAllMessagesForChatOK struct {

	/*
	  In: Body
	*/
	Payload models.Messages `json:"body,omitempty"`
}

// NewGetAllMessagesForChatOK creates GetAllMessagesForChatOK with default headers values
func NewGetAllMessagesForChatOK() *GetAllMessagesForChatOK {

	return &GetAllMessagesForChatOK{}
}

// WithPayload adds the payload to the get all messages for chat o k response
func (o *GetAllMessagesForChatOK) WithPayload(payload models.Messages) *GetAllMessagesForChatOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get all messages for chat o k response
func (o *GetAllMessagesForChatOK) SetPayload(payload models.Messages) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAllMessagesForChatOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.Messages, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetAllMessagesForChatBadRequestCode is the HTTP code returned for type GetAllMessagesForChatBadRequest
const GetAllMessagesForChatBadRequestCode int = 400

/*GetAllMessagesForChatBadRequest Invalid parameter input was passed

swagger:response getAllMessagesForChatBadRequest
*/
type GetAllMessagesForChatBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.InvalidParameterInput `json:"body,omitempty"`
}

// NewGetAllMessagesForChatBadRequest creates GetAllMessagesForChatBadRequest with default headers values
func NewGetAllMessagesForChatBadRequest() *GetAllMessagesForChatBadRequest {

	return &GetAllMessagesForChatBadRequest{}
}

// WithPayload adds the payload to the get all messages for chat bad request response
func (o *GetAllMessagesForChatBadRequest) WithPayload(payload *models.InvalidParameterInput) *GetAllMessagesForChatBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get all messages for chat bad request response
func (o *GetAllMessagesForChatBadRequest) SetPayload(payload *models.InvalidParameterInput) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAllMessagesForChatBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
