// Code generated by go-swagger; DO NOT EDIT.

package messages

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "git.dhbw.chd.cx/savood/backend/models"
)

// GetAllMessagesForChatOKCode is the HTTP code returned for type GetAllMessagesForChatOK
const GetAllMessagesForChatOKCode int = 200

/*GetAllMessagesForChatOK Object found and returned

swagger:response getAllMessagesForChatOK
*/
type GetAllMessagesForChatOK struct {

	/*
	  In: Body
	*/
	Payload models.Messages `json:"body,omitempty"`
}

// NewGetAllMessagesForChatOK creates GetAllMessagesForChatOK with default headers values
func NewGetAllMessagesForChatOK() *GetAllMessagesForChatOK {

	return &GetAllMessagesForChatOK{}
}

// WithPayload adds the payload to the get all messages for chat o k response
func (o *GetAllMessagesForChatOK) WithPayload(payload models.Messages) *GetAllMessagesForChatOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get all messages for chat o k response
func (o *GetAllMessagesForChatOK) SetPayload(payload models.Messages) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAllMessagesForChatOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.Messages, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetAllMessagesForChatNotFoundCode is the HTTP code returned for type GetAllMessagesForChatNotFound
const GetAllMessagesForChatNotFoundCode int = 404

/*GetAllMessagesForChatNotFound Invalid parameter input was passed

swagger:response getAllMessagesForChatNotFound
*/
type GetAllMessagesForChatNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.InvalidParameterInput `json:"body,omitempty"`
}

// NewGetAllMessagesForChatNotFound creates GetAllMessagesForChatNotFound with default headers values
func NewGetAllMessagesForChatNotFound() *GetAllMessagesForChatNotFound {

	return &GetAllMessagesForChatNotFound{}
}

// WithPayload adds the payload to the get all messages for chat not found response
func (o *GetAllMessagesForChatNotFound) WithPayload(payload *models.InvalidParameterInput) *GetAllMessagesForChatNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get all messages for chat not found response
func (o *GetAllMessagesForChatNotFound) SetPayload(payload *models.InvalidParameterInput) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAllMessagesForChatNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
