// Code generated by go-swagger; DO NOT EDIT.

package messages

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetAllChatsHandlerFunc turns a function with the right signature into a get all chats handler
type GetAllChatsHandlerFunc func(GetAllChatsParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAllChatsHandlerFunc) Handle(params GetAllChatsParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetAllChatsHandler interface for that can handle valid get all chats params
type GetAllChatsHandler interface {
	Handle(GetAllChatsParams, interface{}) middleware.Responder
}

// NewGetAllChats creates a new http.Handler for the get all chats operation
func NewGetAllChats(ctx *middleware.Context, handler GetAllChatsHandler) *GetAllChats {
	return &GetAllChats{Context: ctx, Handler: handler}
}

/*GetAllChats swagger:route GET /chats/ messages getAllChats

Get all Chats

*/
type GetAllChats struct {
	Context *middleware.Context
	Handler GetAllChatsHandler
}

func (o *GetAllChats) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetAllChatsParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
