// Code generated by go-swagger; DO NOT EDIT.

package messages

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "git.dhbw.chd.cx/savood/backend/models"
)

// UpdateMessageByIDNoContentCode is the HTTP code returned for type UpdateMessageByIDNoContent
const UpdateMessageByIDNoContentCode int = 204

/*UpdateMessageByIDNoContent Accepted; No response.

swagger:response updateMessageByIdNoContent
*/
type UpdateMessageByIDNoContent struct {
}

// NewUpdateMessageByIDNoContent creates UpdateMessageByIDNoContent with default headers values
func NewUpdateMessageByIDNoContent() *UpdateMessageByIDNoContent {

	return &UpdateMessageByIDNoContent{}
}

// WriteResponse to the client
func (o *UpdateMessageByIDNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// UpdateMessageByIDNotFoundCode is the HTTP code returned for type UpdateMessageByIDNotFound
const UpdateMessageByIDNotFoundCode int = 404

/*UpdateMessageByIDNotFound Invalid parameter input was passed

swagger:response updateMessageByIdNotFound
*/
type UpdateMessageByIDNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.InvalidParameterInput `json:"body,omitempty"`
}

// NewUpdateMessageByIDNotFound creates UpdateMessageByIDNotFound with default headers values
func NewUpdateMessageByIDNotFound() *UpdateMessageByIDNotFound {

	return &UpdateMessageByIDNotFound{}
}

// WithPayload adds the payload to the update message by Id not found response
func (o *UpdateMessageByIDNotFound) WithPayload(payload *models.InvalidParameterInput) *UpdateMessageByIDNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update message by Id not found response
func (o *UpdateMessageByIDNotFound) SetPayload(payload *models.InvalidParameterInput) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateMessageByIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
