// Code generated by go-swagger; DO NOT EDIT.

package messages

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"

	models "git.dhbw.chd.cx/backend/models"
)

// NewUpdateMessageByIDParams creates a new UpdateMessageByIDParams object
// no default values defined in spec.
func NewUpdateMessageByIDParams() UpdateMessageByIDParams {

	return UpdateMessageByIDParams{}
}

// UpdateMessageByIDParams contains all the bound params for the update message by Id operation
// typically these are obtained from a http.Request
//
// swagger:parameters updateMessageById
type UpdateMessageByIDParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*New parameters of the message
	  Required: true
	  In: body
	*/
	Body *models.Message
	/*
	  Required: true
	  In: path
	*/
	ChatID string
	/*
	  Required: true
	  In: path
	*/
	ID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewUpdateMessageByIDParams() beforehand.
func (o *UpdateMessageByIDParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.Message
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("body", "body"))
			} else {
				res = append(res, errors.NewParseError("body", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Body = &body
			}
		}
	} else {
		res = append(res, errors.Required("body", "body"))
	}
	rChatID, rhkChatID, _ := route.Params.GetOK("chatID")
	if err := o.bindChatID(rChatID, rhkChatID, route.Formats); err != nil {
		res = append(res, err)
	}

	rID, rhkID, _ := route.Params.GetOK("id")
	if err := o.bindID(rID, rhkID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindChatID binds and validates parameter ChatID from path.
func (o *UpdateMessageByIDParams) bindChatID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.ChatID = raw

	return nil
}

// bindID binds and validates parameter ID from path.
func (o *UpdateMessageByIDParams) bindID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.ID = raw

	return nil
}
