// Code generated by go-swagger; DO NOT EDIT.

package profile

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// CreateNewProfileHandlerFunc turns a function with the right signature into a create new profile handler
type CreateNewProfileHandlerFunc func(CreateNewProfileParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateNewProfileHandlerFunc) Handle(params CreateNewProfileParams) middleware.Responder {
	return fn(params)
}

// CreateNewProfileHandler interface for that can handle valid create new profile params
type CreateNewProfileHandler interface {
	Handle(CreateNewProfileParams) middleware.Responder
}

// NewCreateNewProfile creates a new http.Handler for the create new profile operation
func NewCreateNewProfile(ctx *middleware.Context, handler CreateNewProfileHandler) *CreateNewProfile {
	return &CreateNewProfile{Context: ctx, Handler: handler}
}

/*CreateNewProfile swagger:route POST /profile profile createNewProfile

Add a new profile

*/
type CreateNewProfile struct {
	Context *middleware.Context
	Handler CreateNewProfileHandler
}

func (o *CreateNewProfile) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCreateNewProfileParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
