// Code generated by go-swagger; DO NOT EDIT.

package profile

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "git.dhbw.chd.cx/savood/backend/models"
)

// CreateNewProfileOKCode is the HTTP code returned for type CreateNewProfileOK
const CreateNewProfileOKCode int = 200

/*CreateNewProfileOK Object found and returned

swagger:response createNewProfileOK
*/
type CreateNewProfileOK struct {

	/*
	  In: Body
	*/
	Payload *models.Profile `json:"body,omitempty"`
}

// NewCreateNewProfileOK creates CreateNewProfileOK with default headers values
func NewCreateNewProfileOK() *CreateNewProfileOK {

	return &CreateNewProfileOK{}
}

// WithPayload adds the payload to the create new profile o k response
func (o *CreateNewProfileOK) WithPayload(payload *models.Profile) *CreateNewProfileOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create new profile o k response
func (o *CreateNewProfileOK) SetPayload(payload *models.Profile) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateNewProfileOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateNewProfileNotFoundCode is the HTTP code returned for type CreateNewProfileNotFound
const CreateNewProfileNotFoundCode int = 404

/*CreateNewProfileNotFound Invalid parameter input was passed

swagger:response createNewProfileNotFound
*/
type CreateNewProfileNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.InvalidParameterInput `json:"body,omitempty"`
}

// NewCreateNewProfileNotFound creates CreateNewProfileNotFound with default headers values
func NewCreateNewProfileNotFound() *CreateNewProfileNotFound {

	return &CreateNewProfileNotFound{}
}

// WithPayload adds the payload to the create new profile not found response
func (o *CreateNewProfileNotFound) WithPayload(payload *models.InvalidParameterInput) *CreateNewProfileNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create new profile not found response
func (o *CreateNewProfileNotFound) SetPayload(payload *models.InvalidParameterInput) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateNewProfileNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
