// Code generated by go-swagger; DO NOT EDIT.

package profile

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// DeleteProfileByIDHandlerFunc turns a function with the right signature into a delete profile by Id handler
type DeleteProfileByIDHandlerFunc func(DeleteProfileByIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteProfileByIDHandlerFunc) Handle(params DeleteProfileByIDParams) middleware.Responder {
	return fn(params)
}

// DeleteProfileByIDHandler interface for that can handle valid delete profile by Id params
type DeleteProfileByIDHandler interface {
	Handle(DeleteProfileByIDParams) middleware.Responder
}

// NewDeleteProfileByID creates a new http.Handler for the delete profile by Id operation
func NewDeleteProfileByID(ctx *middleware.Context, handler DeleteProfileByIDHandler) *DeleteProfileByID {
	return &DeleteProfileByID{Context: ctx, Handler: handler}
}

/*DeleteProfileByID swagger:route DELETE /profile/{id} profile deleteProfileById

Delete a profile

*/
type DeleteProfileByID struct {
	Context *middleware.Context
	Handler DeleteProfileByIDHandler
}

func (o *DeleteProfileByID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteProfileByIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
