// Code generated by go-swagger; DO NOT EDIT.

package profile

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "git.dhbw.chd.cx/savood/backend/models"
)

// DeleteProfileByIDNoContentCode is the HTTP code returned for type DeleteProfileByIDNoContent
const DeleteProfileByIDNoContentCode int = 204

/*DeleteProfileByIDNoContent Removed; No response.

swagger:response deleteProfileByIdNoContent
*/
type DeleteProfileByIDNoContent struct {
}

// NewDeleteProfileByIDNoContent creates DeleteProfileByIDNoContent with default headers values
func NewDeleteProfileByIDNoContent() *DeleteProfileByIDNoContent {

	return &DeleteProfileByIDNoContent{}
}

// WriteResponse to the client
func (o *DeleteProfileByIDNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// DeleteProfileByIDNotFoundCode is the HTTP code returned for type DeleteProfileByIDNotFound
const DeleteProfileByIDNotFoundCode int = 404

/*DeleteProfileByIDNotFound Invalid parameter input was passed

swagger:response deleteProfileByIdNotFound
*/
type DeleteProfileByIDNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.InvalidParameterInput `json:"body,omitempty"`
}

// NewDeleteProfileByIDNotFound creates DeleteProfileByIDNotFound with default headers values
func NewDeleteProfileByIDNotFound() *DeleteProfileByIDNotFound {

	return &DeleteProfileByIDNotFound{}
}

// WithPayload adds the payload to the delete profile by Id not found response
func (o *DeleteProfileByIDNotFound) WithPayload(payload *models.InvalidParameterInput) *DeleteProfileByIDNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete profile by Id not found response
func (o *DeleteProfileByIDNotFound) SetPayload(payload *models.InvalidParameterInput) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteProfileByIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
