// Code generated by go-swagger; DO NOT EDIT.

package profile

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// ProfileIDPutHandlerFunc turns a function with the right signature into a profile Id put handler
type ProfileIDPutHandlerFunc func(ProfileIDPutParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ProfileIDPutHandlerFunc) Handle(params ProfileIDPutParams) middleware.Responder {
	return fn(params)
}

// ProfileIDPutHandler interface for that can handle valid profile Id put params
type ProfileIDPutHandler interface {
	Handle(ProfileIDPutParams) middleware.Responder
}

// NewProfileIDPut creates a new http.Handler for the profile Id put operation
func NewProfileIDPut(ctx *middleware.Context, handler ProfileIDPutHandler) *ProfileIDPut {
	return &ProfileIDPut{Context: ctx, Handler: handler}
}

/*ProfileIDPut swagger:route PUT /profile/{id} profile profileIdPut

Update an profile

*/
type ProfileIDPut struct {
	Context *middleware.Context
	Handler ProfileIDPutHandler
}

func (o *ProfileIDPut) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewProfileIDPutParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
