// Code generated by go-swagger; DO NOT EDIT.

package offering

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// CreateNewOfferingHandlerFunc turns a function with the right signature into a create new offering handler
type CreateNewOfferingHandlerFunc func(CreateNewOfferingParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateNewOfferingHandlerFunc) Handle(params CreateNewOfferingParams) middleware.Responder {
	return fn(params)
}

// CreateNewOfferingHandler interface for that can handle valid create new offering params
type CreateNewOfferingHandler interface {
	Handle(CreateNewOfferingParams) middleware.Responder
}

// NewCreateNewOffering creates a new http.Handler for the create new offering operation
func NewCreateNewOffering(ctx *middleware.Context, handler CreateNewOfferingHandler) *CreateNewOffering {
	return &CreateNewOffering{Context: ctx, Handler: handler}
}

/*CreateNewOffering swagger:route POST /offering offering createNewOffering

Add a new offering

*/
type CreateNewOffering struct {
	Context *middleware.Context
	Handler CreateNewOfferingHandler
}

func (o *CreateNewOffering) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCreateNewOfferingParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
