// Code generated by go-swagger; DO NOT EDIT.

package offering

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetOfferingByIDHandlerFunc turns a function with the right signature into a get offering by Id handler
type GetOfferingByIDHandlerFunc func(GetOfferingByIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetOfferingByIDHandlerFunc) Handle(params GetOfferingByIDParams) middleware.Responder {
	return fn(params)
}

// GetOfferingByIDHandler interface for that can handle valid get offering by Id params
type GetOfferingByIDHandler interface {
	Handle(GetOfferingByIDParams) middleware.Responder
}

// NewGetOfferingByID creates a new http.Handler for the get offering by Id operation
func NewGetOfferingByID(ctx *middleware.Context, handler GetOfferingByIDHandler) *GetOfferingByID {
	return &GetOfferingByID{Context: ctx, Handler: handler}
}

/*GetOfferingByID swagger:route GET /offering/{id} offering getOfferingById

Display an offering

*/
type GetOfferingByID struct {
	Context *middleware.Context
	Handler GetOfferingByIDHandler
}

func (o *GetOfferingByID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetOfferingByIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
