// Code generated by go-swagger; DO NOT EDIT.

package offering

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "git.dhbw.chd.cx/savood/backend/models"
)

// OfferingIDDeleteNoContentCode is the HTTP code returned for type OfferingIDDeleteNoContent
const OfferingIDDeleteNoContentCode int = 204

/*OfferingIDDeleteNoContent Removed; No response.

swagger:response offeringIdDeleteNoContent
*/
type OfferingIDDeleteNoContent struct {
}

// NewOfferingIDDeleteNoContent creates OfferingIDDeleteNoContent with default headers values
func NewOfferingIDDeleteNoContent() *OfferingIDDeleteNoContent {

	return &OfferingIDDeleteNoContent{}
}

// WriteResponse to the client
func (o *OfferingIDDeleteNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// OfferingIDDeleteNotFoundCode is the HTTP code returned for type OfferingIDDeleteNotFound
const OfferingIDDeleteNotFoundCode int = 404

/*OfferingIDDeleteNotFound Invalid parameter input was passed

swagger:response offeringIdDeleteNotFound
*/
type OfferingIDDeleteNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.InvalidParameterInput `json:"body,omitempty"`
}

// NewOfferingIDDeleteNotFound creates OfferingIDDeleteNotFound with default headers values
func NewOfferingIDDeleteNotFound() *OfferingIDDeleteNotFound {

	return &OfferingIDDeleteNotFound{}
}

// WithPayload adds the payload to the offering Id delete not found response
func (o *OfferingIDDeleteNotFound) WithPayload(payload *models.InvalidParameterInput) *OfferingIDDeleteNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the offering Id delete not found response
func (o *OfferingIDDeleteNotFound) SetPayload(payload *models.InvalidParameterInput) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *OfferingIDDeleteNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
