// Code generated by go-swagger; DO NOT EDIT.

package offering

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// OfferingIDPutHandlerFunc turns a function with the right signature into a offering Id put handler
type OfferingIDPutHandlerFunc func(OfferingIDPutParams) middleware.Responder

// Handle executing the request and returning a response
func (fn OfferingIDPutHandlerFunc) Handle(params OfferingIDPutParams) middleware.Responder {
	return fn(params)
}

// OfferingIDPutHandler interface for that can handle valid offering Id put params
type OfferingIDPutHandler interface {
	Handle(OfferingIDPutParams) middleware.Responder
}

// NewOfferingIDPut creates a new http.Handler for the offering Id put operation
func NewOfferingIDPut(ctx *middleware.Context, handler OfferingIDPutHandler) *OfferingIDPut {
	return &OfferingIDPut{Context: ctx, Handler: handler}
}

/*OfferingIDPut swagger:route PUT /offering/{id} offering offeringIdPut

Update an offering

*/
type OfferingIDPut struct {
	Context *middleware.Context
	Handler OfferingIDPutHandler
}

func (o *OfferingIDPut) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewOfferingIDPutParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
