// Code generated by go-swagger; DO NOT EDIT.

package offerings

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "git.dhbw.chd.cx/savood/backend/models"
)

// DeleteOfferingByIDNoContentCode is the HTTP code returned for type DeleteOfferingByIDNoContent
const DeleteOfferingByIDNoContentCode int = 204

/*DeleteOfferingByIDNoContent Removed; No response.

swagger:response deleteOfferingByIdNoContent
*/
type DeleteOfferingByIDNoContent struct {
}

// NewDeleteOfferingByIDNoContent creates DeleteOfferingByIDNoContent with default headers values
func NewDeleteOfferingByIDNoContent() *DeleteOfferingByIDNoContent {

	return &DeleteOfferingByIDNoContent{}
}

// WriteResponse to the client
func (o *DeleteOfferingByIDNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// DeleteOfferingByIDBadRequestCode is the HTTP code returned for type DeleteOfferingByIDBadRequest
const DeleteOfferingByIDBadRequestCode int = 400

/*DeleteOfferingByIDBadRequest Invalid parameter input was passed

swagger:response deleteOfferingByIdBadRequest
*/
type DeleteOfferingByIDBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.InvalidParameterInput `json:"body,omitempty"`
}

// NewDeleteOfferingByIDBadRequest creates DeleteOfferingByIDBadRequest with default headers values
func NewDeleteOfferingByIDBadRequest() *DeleteOfferingByIDBadRequest {

	return &DeleteOfferingByIDBadRequest{}
}

// WithPayload adds the payload to the delete offering by Id bad request response
func (o *DeleteOfferingByIDBadRequest) WithPayload(payload *models.InvalidParameterInput) *DeleteOfferingByIDBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete offering by Id bad request response
func (o *DeleteOfferingByIDBadRequest) SetPayload(payload *models.InvalidParameterInput) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteOfferingByIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteOfferingByIDForbiddenCode is the HTTP code returned for type DeleteOfferingByIDForbidden
const DeleteOfferingByIDForbiddenCode int = 403

/*DeleteOfferingByIDForbidden Generic Error

swagger:response deleteOfferingByIdForbidden
*/
type DeleteOfferingByIDForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorModel `json:"body,omitempty"`
}

// NewDeleteOfferingByIDForbidden creates DeleteOfferingByIDForbidden with default headers values
func NewDeleteOfferingByIDForbidden() *DeleteOfferingByIDForbidden {

	return &DeleteOfferingByIDForbidden{}
}

// WithPayload adds the payload to the delete offering by Id forbidden response
func (o *DeleteOfferingByIDForbidden) WithPayload(payload *models.ErrorModel) *DeleteOfferingByIDForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete offering by Id forbidden response
func (o *DeleteOfferingByIDForbidden) SetPayload(payload *models.ErrorModel) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteOfferingByIDForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteOfferingByIDInternalServerErrorCode is the HTTP code returned for type DeleteOfferingByIDInternalServerError
const DeleteOfferingByIDInternalServerErrorCode int = 500

/*DeleteOfferingByIDInternalServerError Generic Error

swagger:response deleteOfferingByIdInternalServerError
*/
type DeleteOfferingByIDInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorModel `json:"body,omitempty"`
}

// NewDeleteOfferingByIDInternalServerError creates DeleteOfferingByIDInternalServerError with default headers values
func NewDeleteOfferingByIDInternalServerError() *DeleteOfferingByIDInternalServerError {

	return &DeleteOfferingByIDInternalServerError{}
}

// WithPayload adds the payload to the delete offering by Id internal server error response
func (o *DeleteOfferingByIDInternalServerError) WithPayload(payload *models.ErrorModel) *DeleteOfferingByIDInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete offering by Id internal server error response
func (o *DeleteOfferingByIDInternalServerError) SetPayload(payload *models.ErrorModel) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteOfferingByIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
