// Code generated by go-swagger; DO NOT EDIT.

package offerings

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetOfferingsParams creates a new GetOfferingsParams object
// no default values defined in spec.
func NewGetOfferingsParams() GetOfferingsParams {

	return GetOfferingsParams{}
}

// GetOfferingsParams contains all the bound params for the get offerings operation
// typically these are obtained from a http.Request
//
// swagger:parameters getOfferings
type GetOfferingsParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Filteres offerings by owned or requested
	  In: query
	*/
	Filter *string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetOfferingsParams() beforehand.
func (o *GetOfferingsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qFilter, qhkFilter, _ := qs.GetOK("filter")
	if err := o.bindFilter(qFilter, qhkFilter, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindFilter binds and validates parameter Filter from query.
func (o *GetOfferingsParams) bindFilter(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.Filter = &raw

	if err := o.validateFilter(formats); err != nil {
		return err
	}

	return nil
}

// validateFilter carries on validations for parameter Filter
func (o *GetOfferingsParams) validateFilter(formats strfmt.Registry) error {

	if err := validate.Enum("filter", "query", *o.Filter, []interface{}{"owned", "requested"}); err != nil {
		return err
	}

	return nil
}
