// Code generated by go-swagger; DO NOT EDIT.

package offerings

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "git.dhbw.chd.cx/backend/models"
)

// GetOfferingsOKCode is the HTTP code returned for type GetOfferingsOK
const GetOfferingsOKCode int = 200

/*GetOfferingsOK Object found and returned

swagger:response getOfferingsOK
*/
type GetOfferingsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Offering `json:"body,omitempty"`
}

// NewGetOfferingsOK creates GetOfferingsOK with default headers values
func NewGetOfferingsOK() *GetOfferingsOK {

	return &GetOfferingsOK{}
}

// WithPayload adds the payload to the get offerings o k response
func (o *GetOfferingsOK) WithPayload(payload []*models.Offering) *GetOfferingsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get offerings o k response
func (o *GetOfferingsOK) SetPayload(payload []*models.Offering) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetOfferingsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]*models.Offering, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetOfferingsBadRequestCode is the HTTP code returned for type GetOfferingsBadRequest
const GetOfferingsBadRequestCode int = 400

/*GetOfferingsBadRequest Invalid parameter input was passed

swagger:response getOfferingsBadRequest
*/
type GetOfferingsBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.InvalidParameterInput `json:"body,omitempty"`
}

// NewGetOfferingsBadRequest creates GetOfferingsBadRequest with default headers values
func NewGetOfferingsBadRequest() *GetOfferingsBadRequest {

	return &GetOfferingsBadRequest{}
}

// WithPayload adds the payload to the get offerings bad request response
func (o *GetOfferingsBadRequest) WithPayload(payload *models.InvalidParameterInput) *GetOfferingsBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get offerings bad request response
func (o *GetOfferingsBadRequest) SetPayload(payload *models.InvalidParameterInput) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetOfferingsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
