// Code generated by go-swagger; DO NOT EDIT.

package offerings

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "git.dhbw.chd.cx/backend/models"
)

// GetOfferingByIDOKCode is the HTTP code returned for type GetOfferingByIDOK
const GetOfferingByIDOKCode int = 200

/*GetOfferingByIDOK Object found and returned

swagger:response getOfferingByIdOK
*/
type GetOfferingByIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Offering `json:"body,omitempty"`
}

// NewGetOfferingByIDOK creates GetOfferingByIDOK with default headers values
func NewGetOfferingByIDOK() *GetOfferingByIDOK {

	return &GetOfferingByIDOK{}
}

// WithPayload adds the payload to the get offering by Id o k response
func (o *GetOfferingByIDOK) WithPayload(payload *models.Offering) *GetOfferingByIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get offering by Id o k response
func (o *GetOfferingByIDOK) SetPayload(payload *models.Offering) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetOfferingByIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetOfferingByIDBadRequestCode is the HTTP code returned for type GetOfferingByIDBadRequest
const GetOfferingByIDBadRequestCode int = 400

/*GetOfferingByIDBadRequest Invalid parameter input was passed

swagger:response getOfferingByIdBadRequest
*/
type GetOfferingByIDBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.InvalidParameterInput `json:"body,omitempty"`
}

// NewGetOfferingByIDBadRequest creates GetOfferingByIDBadRequest with default headers values
func NewGetOfferingByIDBadRequest() *GetOfferingByIDBadRequest {

	return &GetOfferingByIDBadRequest{}
}

// WithPayload adds the payload to the get offering by Id bad request response
func (o *GetOfferingByIDBadRequest) WithPayload(payload *models.InvalidParameterInput) *GetOfferingByIDBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get offering by Id bad request response
func (o *GetOfferingByIDBadRequest) SetPayload(payload *models.InvalidParameterInput) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetOfferingByIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
