// Code generated by go-swagger; DO NOT EDIT.

package offerings

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	models "git.dhbw.chd.cx/backend/models"
)

// UpdateOfferingByIDHandlerFunc turns a function with the right signature into a update offering by Id handler
type UpdateOfferingByIDHandlerFunc func(UpdateOfferingByIDParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateOfferingByIDHandlerFunc) Handle(params UpdateOfferingByIDParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// UpdateOfferingByIDHandler interface for that can handle valid update offering by Id params
type UpdateOfferingByIDHandler interface {
	Handle(UpdateOfferingByIDParams, *models.Principal) middleware.Responder
}

// NewUpdateOfferingByID creates a new http.Handler for the update offering by Id operation
func NewUpdateOfferingByID(ctx *middleware.Context, handler UpdateOfferingByIDHandler) *UpdateOfferingByID {
	return &UpdateOfferingByID{Context: ctx, Handler: handler}
}

/*UpdateOfferingByID swagger:route PATCH /offerings/{id} offerings updateOfferingById

Update an offering

*/
type UpdateOfferingByID struct {
	Context *middleware.Context
	Handler UpdateOfferingByIDHandler
}

func (o *UpdateOfferingByID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewUpdateOfferingByIDParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
