// Code generated by go-swagger; DO NOT EDIT.

package models

import "io"

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// GetUsersIDImageJpegOKBody get users Id image jpeg o k body
// swagger:model getUsersIdImageJpegOKBody
type GetUsersIDImageJpegOKBody io.ReadCloser
