// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// OfferingLocation offering location
// swagger:model offeringLocation
type OfferingLocation struct {

	// longitude then latidue as floats
	Coordinates []float64 `json:"coordinates"`

	// type
	Type string `json:"type,omitempty"`
}

// Validate validates this offering location
func (m *OfferingLocation) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OfferingLocation) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OfferingLocation) UnmarshalBinary(b []byte) error {
	var res OfferingLocation
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
