// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Offering offering
// swagger:model Offering
type Offering struct {

	// avatar url
	AvatarURL string `json:"avatar-url,omitempty"`

	// best by date
	// Format: date
	BestByDate strfmt.Date `json:"best-by-date,omitempty"`

	// creator id
	CreatorID int64 `json:"creator-id,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`

	// location
	Location string `json:"location,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// requested by
	RequestedBy int64 `json:"requested-by,omitempty"`
}

// Validate validates this offering
func (m *Offering) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBestByDate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Offering) validateBestByDate(formats strfmt.Registry) error {

	if swag.IsZero(m.BestByDate) { // not required
		return nil
	}

	if err := validate.FormatOf("best-by-date", "body", "date", m.BestByDate.String(), formats); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Offering) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Offering) UnmarshalBinary(b []byte) error {
	var res Offering
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
