// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/globalsign/mgo/bson"

	"github.com/go-openapi/swag"
)

// UserShort user short
// swagger:model UserShort
type UserShort struct {

	// id
	ID bson.ObjectId `json:"_id,omitempty"`

	// avatar Id
	AvatarID string `json:"avatarId,omitempty"`

	// firstname
	Firstname string `json:"firstname,omitempty"`

	// lastname
	Lastname string `json:"lastname,omitempty"`
}

// Validate validates this user short
func (m *UserShort) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UserShort) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserShort) UnmarshalBinary(b []byte) error {
	var res UserShort
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
